// Generated by scripts/amalgamate.py. Do not edit.

// Begin cljonic-core.hpp
#ifndef CLJONIC_CORE_HPP
#define CLJONIC_CORE_HPP

// Begin cljonic-config.hpp
#pragma once

#if !defined(CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT)
#define CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT 1000
#endif

#define CLJONIC_STRINGIFY_INNER(x) #x
#define CLJONIC_STRINGIFY(x) CLJONIC_STRINGIFY_INNER(x)// End cljonic-config.hpp

/** \mainpage
 * \b cljonic is a \b header-only C++ library designed to allow an \b embedded
 * \b systems C++ developer to program in a \b Functional \b Programming \b
 * Style using a set of functions \b similar in \b name and \b function to \b
 * Clojure. To address the embedded systems focus, \b cljonic \b DOES \b NOT use
 * the heap or exceptions, and uses \b Modern \b C++ features to \b protect , \b
 * guide , and \b teach C++ developers. Finally, \b cljonic is a library that
 * includes unit tests with nearly <b>100% coverage</b>, and is designed to be
 * efficiently maintained.
 *
 * The motivation for \b cljonic comes from observations made about the
 * pragmatic use of C++ for embedded systems software development, the
 * progression of the C++ language (e.g., C++11, C++14, C++17, C++20, C++23),
 * and the counsel of software development "experts", in many different
 * programming languages, that <b>a functional programming style should be
 * eagerly embraced by all developers</b>.
 *
 * Many embedded systems C++ developers are <b>not academic programming language
 * experts</b> with in-depth knowledge of every C++ feature, and many <b>may not
 * have time</b> to follow the progression of the language.  Rather, many
 * embedded systems C++ developers have <b>strong hardware backgrounds</B>, and
 * <B>know a pragmatic specific subset of C++</B> that is often sufficient to
 * deliver reasonably good software in a predictable amount of time, though this
 * is often <b>not optimized for minimal long term cost of ownership</b>.
 * Generally speaking, many C++ developers use a subset of the \b C programming
 * language with some of C++'s <b>Object Oriented</b> capabilities.  This begs a
 * question:
 *
 * <b>Is there a pragmatic subset of Modern C++ that enables embedded systems
 * developers to produce higher-quality, more efficient, and more maintainable
 * code?</b>
 *
 * Changes to C++ have provided valuable capabilities that are time consuming to
 * master, hence it is both <b> valuable to development organizations</b> for
 * their developers to use modern C++ capabilities, and <b> too expensive to
 * train</b> all of their developers to be experts in their use.  This, too,
 * begs a question:
 *
 * <b>Can one or two embedded systems software developers cost-effectively
 * introduce modern C++ capabilities to the entire team?</b>
 *
 * In this post:
 *
 *     https://www.gamedeveloper.com/programming/in-depth-functional-programming-in-c-
 *
 * the author makes the following statements:
 *
 * <b>"A large fraction of the flaws in software development are due to
 * programmers not fully understanding all the possible states their code may
 * execute in. In a multithreaded environment, the lack of understanding and the
 *  resulting problems are greatly amplified, almost to the point of panic if
 * you are paying attention. Programming in a functional style makes the state
 * presented to your code explicit, which makes it much easier to reason about
 *  [(i.e., Fewer mistakes, and less debugging)], and, in a completely pure
 * system, makes thread race conditions impossible."
 *
 * "No matter what language you work in, programming in a functional style
 * provides benefits. You should do it whenever it is convenient, and you should
 * think hard about the decision when it isn't convenient."</b>
 *
 * \b cljonic is a \b header-only library that utilizes \b Modern \b C++
 * capabilities to provide a functional style C++ \b Clojure subset to \b
 * embedded \b systems developers, promotes the \b predictable \b development of
 * \b higher \b quality code \b faster, and can be \b cost-effectively \b
 * maintained over time.
 *
 * \anchor Core_Cheatsheet
 * ___
 * # Cheatsheet
 *
 * ## Aliases
 *
 * | Namespace | "using" C++ Statement |
 * |-----------|-------------------------|
 * | \ref Namespace_Core "core" | using **core** = cljonic::core; |
 * | \ref Namespace_Regex "regex" | using **regex** = cljonic::regex; |
 * | \ref Namespace_Set "set" | using **set** = cljonic::set; |
 * | \ref Namespace_String "string" | using **string** = cljonic::string; |
 *
 * ## Collection Types
 *
 * - \ref Vector "cljonic::Vector"
 * - \ref Range  "cljonic::Range"
 * - \ref Repeat "cljonic::Repeat"
 * - \ref Set    "cljonic::Set"
 * - \ref String "cljonic::String"
 *
 * ## Core Functions
 *
 * ### Composition
 *
 * - \ref Core_Partial "Partial"
 *
 * ### Control
 *
 * - \ref Core_DoSeq "DoSeq", \ref Core_DoTimes "DoTimes", \ref Core_If "If",
 * \ref Core_Unless "Unless", \ref Core_When "When", \ref Core_WhenNot "WhenNot"
 *
 * ### Predicate
 *
 * - \ref Core_Compare "Compare"
 * - \ref Core_EQ "EQ"
 * - \ref Core_GE "GE", \ref Core_GT "GT"
 * - \ref Core_IsAlpha "IsAlpha", \ref Core_IsAlphanumeric "IsAlphanumeric",
 * \ref Core_IsBlank "IsBlank", \ref Core_IsControl "IsControl", \ref
 * Core_IsDigit "IsDigit", \ref Core_IsEven "IsEven", \ref Core_IsGraphical
 * "IsGraphical", \ref Core_IsHexDigit "IsHexDigit", \ref Core_IsLowercase
 * "IsLowercase", \ref Core_IsNatural "IsNatural", \ref Core_IsNegative
 * "IsNegative", \ref Core_IsOdd "IsOdd", \ref Core_IsPositive "IsPositive",
 * \ref Core_IsPrintable "IsPrintable", \ref Core_IsPunctuation "IsPunctuation",
 * \ref Core_IsSpace "IsSpace", \ref Core_IsUppercase "IsUppercase", \ref
 * Core_IsZero "IsZero"
 * - \ref Core_LE "LE", \ref Core_LT "LT"
 * - \ref Core_NE "NE"
 *
 * ### Primitive
 *
 * - \ref Core_Abs "Abs", \ref Core_Add "Add"
 * - \ref Core_Char "Char", \ref Core_Combinations "Combinations", \ref
 * Core_CString "CString"
 * - \ref Core_Dec "Dec", \ref Core_Div "Div"
 * - \ref Core_Factorial "Factorial"
 * - \ref Core_Inc "Inc"
 * - \ref Core_Lowercase "Lowercase"
 * - \ref Core_Max "Max", \ref Core_Min "Min", \ref Core_Mod "Mod", \ref
 * Core_Mul "Mul"
 * - \ref Core_Ord "Ord"
 * - \ref Core_Permutations "Permutations"
 * - \ref Core_Sub "Sub",
 * - \ref Core_Uppercase "Uppercase"
 *
 * ### Seq (i.e., Sequence: Array, Range, Repeat, Set, And/Or String)
 *
 * - \ref Core_Compose "Compose", \ref Core_Concat "Concat", \ref Core_Conj
 * "Conj", \ref Core_Conj_M "Conj_M", \ref Core_Count "Count", \ref Core_Count_M
 * "Count_M", \ref Core_Cycle "Cycle"
 * - \ref Core_Dedupe "Dedupe", \ref Core_DedupeBy "DedupeBy", \ref
 * Core_DefaultElement "DefaultElement", \ref Core_DefaultElement_M
 * "DefaultElement_M", \ref Core_Different "Different", \ref Core_Distinct
 * "Distinct", \ref Core_DistinctBy "DistinctBy", \ref Core_Drop "Drop", \ref
 * Core_DropLast "DropLast", \ref Core_DropWhile "DropWhile"
 * - \ref Core_Empty_M "Empty_M", \ref Core_Equal "Equal", \ref Core_EqualBy
 * "EqualBy", \ref Core_Every "Every"
 * - \ref Core_Filter "Filter", \ref Core_First "First", \ref Core_Flatten
 * "Flatten", \ref Core_FlattenSize "FlattenSize", \ref Core_Frequencies
 * "Frequencies", \ref Core_FrequenciesBy "FrequenciesBy"
 * - \ref Core_Identical "Identical", \ref Core_Identity "Identity", \ref
 * Core_IndexOf "IndexOf", \ref Core_IndexOfBy "IndexOfBy", \ref Core_Interleave
 * "Interleave", \ref Core_Interpose "Interpose", \ref Core_IsDistinct
 * "IsDistinct", \ref Core_IsDistinctBy "IsDistinctBy", \ref Core_IsEmpty
 * "IsEmpty", \ref Core_IsFull "IsFull", \ref Core_Iterate "Iterate"
 * - \ref Core_Juxt "Juxt"
 * - \ref Core_Last "Last", \ref Core_LastIndexOf "LastIndexOf", \ref
 * Core_LastIndexOfBy "LastIndexOfBy"
 * - \ref Core_Map "Map", \ref Core_Max "Max", \ref Core_MaxBy "MaxBy", \ref
 * Core_Min "Min", \ref Core_MinBy "MinBy"
 * - \ref Core_NotAny "NotAny", \ref Core_NotEvery "NotEvery", \ref Core_Nth
 * "Nth", \ref Core_Nth_M "Nth_M"
 * - \ref Core_Partition "Partition", \ref Core_PartitionAll "PartitionAll",
 * \ref Core_PartitionBy "PartitionBy"
 * - \ref Core_Reduce "Reduce", \ref Core_Reductions "Reductions", \ref
 * Core_Remove "Remove", \ref Core_Replace "Replace", \ref Core_Reverse
 * "Reverse"
 * - \ref Core_Second "Second", \ref Core_Seq "Seq", \ref Core_Size "Size", \ref
 * Core_Some "Some", \ref Core_Sort "Sort", \ref Core_SortBy "SortBy", \ref
 * Core_SplitAt "SplitAt", \ref Core_SplitWith "SplitWith", \ref Core_Subs
 * "Subs"
 * - \ref Core_ValidIndex "valid_index"
 * - \ref Core_Take "Take", \ref Core_TakeLast "TakeLast", \ref Core_TakeNth
 * "TakeNth", \ref Core_TakeWhile "TakeWhile"
 *
 * ## Regex Functions
 *
 * - \ref Regex_ReFind "ReFind", \ref Regex_ReSeq "ReSeq"
 *
 * ## Set Functions
 *
 * - \ref Set_Conj "Conj", \ref Set_ConjBy "ConjBy", \ref Set_Contains
 * "Contains", \ref Set_ContainsBy "ContainsBy"
 * - \ref Set_Difference "Difference", \ref Set_DifferenceBy "DifferenceBy",
 * \ref Set_Disj "Disj", \ref Set_DisjBy "DisjBy"
 * - \ref Set_IndexOf "IndexOf", \ref Set_IndexOfBy "IndexOfBy", \ref
 * Set_Intersection "Intersection", \ref Set_IntersectionBy "IntersectionBy"
 * - \ref Set_ToSet "ToSet", \ref Set_ToSetBy "ToSetBy"
 * - \ref Set_Union "Union", \ref Set_UnionBy "UnionBy"
 *
 * ## String Functions
 *
 * - \ref String_Capitalize "Capitalize", \ref String_Compare "Compare", \ref
 * String_Concat "Concat"
 * - \ref String_EndsWith "EndsWith"
 * - \ref String_FloatToString "FloatToString", \ref String_Format "Format"
 * - \ref String_Includes "Includes", \ref String_IndexOf "IndexOf", \ref
 * String_Interpose "Interpose", \ref String_IntToString "IntToString", \ref
 * String_IntToStringHex "IntToStringHex", \ref String_IsBlank "IsBlank"
 * - \ref String_LastIndexOf "LastIndexOf", \ref String_Lowercase "Lowercase"
 * - \ref String_Partition "Partition", \ref String_PartitionAll "PartitionAll",
 * \ref String_PartitionBy "PartitionBy"
 * - \ref String_Replace "Replace", \ref String_ReplaceFirst "ReplaceFirst"
 * - \ref String_Split "Split", \ref String_SplitCount "SplitCount", \ref
 * String_SplitLine "SplitLine", \ref String_StartsWith "StartsWith", \ref
 * String_StrLen "StrLen", \ref String_StrOfChar "StrOfChar", \ref
 * String_StrToFloat "StrToFloat", \ref String_StrToIntDecimal
 * "StrToIntDecimal", \ref String_StrToIntHex "StrToIntHex", \ref String_Subs
 * "Subs"
 * - \ref String_Trim "Trim", \ref String_TrimLeft "TrimLeft", \ref
 * String_TrimNewLine "TrimNewLine", \ref String_TrimRight "TrimRight"
 * - \ref String_Uppercase "Uppercase"
 */

/** \anchor Namespace_Core
 * The \b Core namespace provides the vast majority of \b cljonic functions.
 * Many \b Core functions deal with \ref Array, \ref Range, \ref Repeat, \ref
 * Set, and \ref String, collections. The variety and capability of the \b Core
 * functions provide much of the overall value of the <b>cljonic functional
 * style of programming</b>.
 */

// Begin cljonic-concepts.hpp
#pragma once

#include <concepts>
#include <cstddef>

namespace cljonic::concepts {

/** Requires that \p value_type is default-initializable and copyable - the
 * minimum contract for current Vector element storage semantics.
 */
template <typename value_type>
concept VectorElement =
    std::default_initializable<value_type> && std::copyable<value_type>;

/** Requires that Vector storage can be initialized and assigned without
 * throwing.
 */
template <typename value_type>
concept NothrowVectorElement =
    VectorElement<value_type> &&
    requires(value_type value, const value_type &other) {
      { value_type{} } noexcept;
      { value_type{other} } noexcept;
      { value = other } noexcept;
    };

/** Requires that an argument is implicitly convertible to and can construct a
 * Vector element without throwing.
 */
template <typename value_type, typename argument_type>
concept NothrowElementConstruction =
    std::convertible_to<argument_type, value_type> &&
    requires(argument_type argument) {
      { argument_type{argument} } noexcept;
      { value_type{argument} } noexcept;
    };

/** Requires that \p collection_type exposes a \c size() member returning a
 * count of logical elements.
 */
template <typename collection_type>
concept Collection = requires(const collection_type &c) {
  { c.size() } -> std::same_as<std::size_t>;
};

} // namespace cljonic::concepts
// End cljonic-concepts.hpp
// Begin cljonic-core-collection-maximum-element-count.hpp
#pragma once

#include <cstddef>


namespace cljonic {

/** \anchor CollectionMaximumElementCountValue
 * \b CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT_VALUE is a constexpr constant
 * that captures the configured synthesis ceiling for bounded cljonic
 * collections and semantically infinite producers. This type-safe constant
 * can be used in compile-time expressions, static assertions, and constexpr
 * functions while remaining fully overridable via the
 * CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT macro.
 */
constexpr std::size_t CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT_VALUE =
    CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT;

/** \anchor Core_CollectionMaximumElementCount
 * \b collection_maximum_element_count returns the configured synthesis
 * ceiling for bounded cljonic collections and semantically infinite
 * producers.
 */
[[nodiscard]] constexpr auto
collection_maximum_element_count() noexcept -> std::size_t {
  return CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT_VALUE;
}

} // namespace cljonic
// End cljonic-core-collection-maximum-element-count.hpp
// Begin cljonic-core-count.hpp
#pragma once


namespace cljonic
{

  /** \anchor Core_Count
   * \b count returns the number of logical elements in \p collection.
   *
   ~~~~~{.cpp}
   #include "cljonic.hpp"
   using namespace cljonic;

   int main() {
     const auto empty = Vector<int, 4>{};
     const auto populated = Vector{1, 2};

     const auto n0 = count(empty);     // 0
     const auto n1 = count(populated); // 2

     return (n0 == 0 && n1 == 2) ? 0 : 1;
   }
   ~~~~~
   */
  template <concepts::Collection collection_type>
  [[nodiscard]] constexpr auto
  count(const collection_type &collection) noexcept -> std::size_t
  {
    return collection.size();
  }

} // namespace cljonic
// End cljonic-core-count.hpp
// Begin cljonic-core-get.hpp
#pragma once

// Begin cljonic-core-valid-index.hpp
#pragma once

#include <concepts>
#include <cstddef>

// Begin cljonic-range.hpp
#pragma once

#include <concepts>
#include <cstddef>
#include <type_traits>


namespace cljonic
{

    /** \anchor Range
     * \b Range is a bounded integer producer that represents a sequence from
     * \p start up to but excluding \p end, advancing by \p step. The supported
     * subset is intentionally limited to integral types with explicit defaulting
     * and bounded materialization. \p value_type defaults to \c int, so
     * \c Range{} is equivalent to Clojure's <tt>(range)</tt>.
     *
     * This example covers the supported construction forms and free-function
     * observation. Range has no member accessors for start, end, or step, and
     * canonical observation is free-function-first via \c count and \c empty.
     *
     ~~~~~{.cpp}
     #include "cljonic.hpp"
     using namespace cljonic;

     int main() {
       constexpr Range zero_start_unit_step{};
       constexpr Range ascending{0, 10};
       constexpr Range descending{10, 0, -2};
       constexpr Range empty_range{5, 5, 1};
       constexpr Range zero_step{3, 9, 0};

       static_assert(count(zero_start_unit_step) ==
                     collection_maximum_element_count());
       static_assert(count(ascending) == 10U);
       static_assert(count(descending) == 5U);
       static_assert(empty_range.empty());
       static_assert(valid_index(ascending, 9));
       static_assert(!valid_index(ascending, 10));
       // A zero step is semantically infinite: it repeats start and is bounded
       // by the synthesis cap rather than reporting a true finite cardinality.
       static_assert(count(zero_step) == collection_maximum_element_count());

       return 0;
     }
     ~~~~~
     */
    template <std::integral value_type = int>
    class Range
    {
    public:
        using element_type = value_type;

        static_assert(std::integral<value_type>,
                      "Range requires an integral element type");

        constexpr Range() noexcept
            : start_{0}, end_{collection_maximum_element_count()}, step_{1},
              size_{collection_maximum_element_count()} {}

        constexpr explicit Range(value_type end) noexcept
            requires std::integral<value_type>
            : Range(value_type{0}, end, value_type{1})
        {
        }

        constexpr Range(value_type start, value_type end) noexcept
            requires std::integral<value_type>
            : Range(start, end, value_type{1})
        {
        }

        constexpr Range(value_type start, value_type end, value_type step) noexcept
            requires std::integral<value_type>
            : start_{start}, end_{end}, step_{step},
              size_{compute_size(start, end, step)}
        {
            if (step == value_type{0})
            {
                start_ = start;
                end_ = end;
                step_ = step;
                size_ = collection_maximum_element_count();
            }
        }

        // Reject construction from any argument type that isn't exactly value_type,
        // so mismatched integral/floating-point arguments fail to compile instead
        // of silently truncating via implicit conversion.
        template <typename T>
            requires(!std::same_as<T, value_type>)
        constexpr Range(T) noexcept = delete;

        template <typename T, typename U>
            requires(!std::same_as<T, value_type> || !std::same_as<U, value_type>)
        constexpr Range(T, U) noexcept = delete;

        template <typename T, typename U, typename V>
            requires(!std::same_as<T, value_type> || !std::same_as<U, value_type> ||
                     !std::same_as<V, value_type>)
        constexpr Range(T, U, V) noexcept = delete;

        [[nodiscard]] constexpr auto size() const noexcept -> std::size_t
        {
            return size_;
        }

        [[nodiscard]] constexpr auto empty() const noexcept -> bool
        {
            return size_ == 0U;
        }

    private:
        // Deliberately not defined: calling this during constant evaluation makes
        // that evaluation ill-formed, turning an oversized constexpr Range into a
        // compile-time error instead of a silently clamped bounded prefix. This
        // path is unreachable at runtime, so it is never actually linked.
        static void reject_oversized_range_in_constant_expression() noexcept;

        [[nodiscard]] static constexpr auto
        clamp_to_synthesis_cap(std::size_t computed_size) noexcept -> std::size_t
        {
            if (computed_size > collection_maximum_element_count())
            {
                if consteval
                {
                    reject_oversized_range_in_constant_expression();
                }
                return collection_maximum_element_count();
            }
            return computed_size;
        }

        [[nodiscard]] static constexpr auto
        compute_positive_step_size(value_type start, value_type end,
                                   value_type step) noexcept -> std::size_t
        {
            if (start >= end)
            {
                return 0U;
            }
            using unsigned_type = std::make_unsigned_t<value_type>;
            const auto delta =
                static_cast<unsigned_type>(end) - static_cast<unsigned_type>(start);
            const auto positive_step = static_cast<unsigned_type>(step);
            const auto computed_size = static_cast<std::size_t>(delta / positive_step) +
                                       (delta % positive_step == 0U ? 0U : 1U);
            return clamp_to_synthesis_cap(computed_size);
        }

        [[nodiscard]] static constexpr auto
        compute_negative_step_size(value_type start, value_type end,
                                   value_type step) noexcept -> std::size_t
        {
            if (start <= end)
            {
                return 0U;
            }
            using unsigned_type = std::make_unsigned_t<value_type>;
            const auto magnitude =
                static_cast<unsigned_type>(0) - static_cast<unsigned_type>(step);
            const auto delta =
                static_cast<unsigned_type>(start) - static_cast<unsigned_type>(end);
            const auto computed_size = static_cast<std::size_t>(delta / magnitude) +
                                       (delta % magnitude == 0U ? 0U : 1U);
            return clamp_to_synthesis_cap(computed_size);
        }

        static constexpr auto compute_size(value_type start, value_type end,
                                           value_type step) noexcept -> std::size_t
        {
            if (step == value_type{0})
            {
                return collection_maximum_element_count();
            }

            return step > value_type{0} ? compute_positive_step_size(start, end, step)
                                        : compute_negative_step_size(start, end, step);
        }

        value_type start_;
        value_type end_;
        value_type step_;
        std::size_t size_;
    };

    template <std::integral integer_type>
    Range(integer_type) -> Range<integer_type>;

    template <std::integral integer_type>
    Range(integer_type, integer_type) -> Range<integer_type>;

    template <std::integral integer_type>
    Range(integer_type, integer_type, integer_type) -> Range<integer_type>;

} // namespace cljonic
// End cljonic-range.hpp
// Begin cljonic-vector.hpp
#pragma once

#include <array>
#include <cstddef>
#include <utility>


namespace cljonic
{

  /** \anchor Vector
   * \b Vector is a CopyOnModifyCollection with fixed-capacity storage.
   * Construction with more initializers than capacity is a compile-time error.
   *
   * This example covers bounded construction and indexed observation. Free
   * functions that operate on collections are documented with their own headers.
   *
   ~~~~~{.cpp}
   #include "cljonic.hpp"
   using namespace cljonic;

   struct Pixel {
     int x;
     int y;
   };

   using Inner = Vector<int, 2>;

   int main() {
     [[maybe_unused]] constexpr auto ints_at_capacity = Vector{1, 2, 3};
     [[maybe_unused]] constexpr auto ints_populated = Vector<int, 4>{1, 2};
     [[maybe_unused]] constexpr auto ints_empty = Vector<int, 4>{};
     constexpr auto doubles_populated = Vector<double, 3>{1.5, 2.5};
     constexpr auto pixels_populated = Vector{Pixel{1, 2}, Pixel{3, 4}};
     [[maybe_unused]] constexpr auto nested_int_vectors =
         Vector{Vector<int, 2>{1, 2}, Vector<int, 2>{3}};
     [[maybe_unused]] constexpr auto nested_alias_vectors =
         Vector{Inner{4, 5}, Inner{6}};

     constexpr Vector<int, 4> values{10, 20};
     static_assert(values(0U) == 10);
     static_assert(values(2U) == 0);
     static_assert(values(2U, 99) == 99);
     static_assert(std::same_as<decltype(doubles_populated(0U)), double>);
     static_assert(pixels_populated(0U).x == 1);
     static_assert(pixels_populated(1U).y == 4);

     return 0;
   }
   ~~~~~
   */
  template <concepts::VectorElement element_type, std::size_t capacity_value>
  class Vector
  {
  public:
    using value_type = element_type;

    static_assert(concepts::NothrowVectorElement<element_type>,
                  "Vector element storage operations must not throw");

    static_assert(capacity_value <=
                      cljonic::CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT_VALUE,
                  "Vector capacity exceeds "
                  "CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT=" CLJONIC_STRINGIFY(
                      CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT));

    template <typename... Args>
    constexpr Vector(Args... args) noexcept(
        concepts::NothrowVectorElement<element_type> &&
        (concepts::NothrowElementConstruction<element_type, Args> && ...))
        : storage_{}, logical_size_{0}
    {
      static_assert(sizeof...(Args) <= capacity_value,
                    "Vector constructor requires initializer count to be less "
                    "than or equal to capacity");
      static_assert(
          (concepts::NothrowElementConstruction<element_type, Args> && ...),
          "Vector constructor requires all arguments to construct "
          "element_type without throwing and be implicitly "
          "convertible to element_type");

      initialize_storage_if_valid(args...);
    }

    [[nodiscard]] static constexpr auto capacity() noexcept -> std::size_t
    {
      return capacity_value;
    }

    [[nodiscard]] constexpr auto size() const noexcept -> std::size_t
    {
      return logical_size_;
    }

    template <std::integral index_type>
    [[nodiscard]] constexpr auto
    operator()(index_type index) const noexcept -> value_type
    {
      return index_is_valid(index) ? storage_[static_cast<std::size_t>(index)]
                                   : value_type{};
    }

    template <std::integral index_type>
    [[nodiscard]] constexpr auto
    operator()(index_type index,
               const value_type &fallback) const noexcept -> value_type
    {
      return index_is_valid(index) ? storage_[static_cast<std::size_t>(index)]
                                   : fallback;
    }

  private:
    template <std::integral index_type>
    [[nodiscard]] constexpr auto
    index_is_valid(index_type index) const noexcept -> bool
    {
      if constexpr (std::signed_integral<index_type>)
      {
        if (index < 0)
        {
          return false;
        }
      }

      return static_cast<std::size_t>(index) < logical_size_;
    }

    template <typename... Args>
    static constexpr bool constructor_arguments_valid =
        sizeof...(Args) <= capacity_value &&
        concepts::NothrowVectorElement<element_type> &&
        (concepts::NothrowElementConstruction<element_type, Args> && ...);

    template <typename... Args>
    constexpr void initialize_storage_if_valid(Args... args) noexcept
    {
      if constexpr (constructor_arguments_valid<Args...>)
      {
        initialize_storage(std::index_sequence_for<Args...>{}, args...);
        logical_size_ = sizeof...(Args);
      }
    }

    template <std::size_t... Indices, typename... Args>
    constexpr void initialize_storage(std::index_sequence<Indices...>,
                                      Args... args) noexcept
    {
      ((storage_[Indices] = element_type{args}), ...);
    }

    std::array<value_type, capacity_value> storage_{};
    std::size_t logical_size_ = 0;
  };

  template <typename First, typename... Rest>
  Vector(First, Rest...) -> Vector<First, 1 + sizeof...(Rest)>;

} // namespace cljonic
// End cljonic-vector.hpp

namespace cljonic
{

  /** \anchor Core_ValidIndex
   * \b valid_index reports whether an integral index addresses a logical
   * element in a Vector or Range without inspecting the produced value.
   *
   ~~~~~{.cpp}
   #include "cljonic.hpp"
   using namespace cljonic;

   int main() {
     constexpr Vector<int, 4> values{10, 20};

     static_assert(valid_index(values, 1U));
     static_assert(!valid_index(values, 2U));
     static_assert(!valid_index(values, -1));

     constexpr Range<int> range{0, 10};

     static_assert(valid_index(range, 9));
     static_assert(!valid_index(range, 10));
     static_assert(!valid_index(range, -1));

     return 0;
   }
   ~~~~~
   */
  template <typename element_type, std::size_t capacity_value,
            std::integral index_type>
  [[nodiscard]] constexpr auto
  valid_index(const Vector<element_type, capacity_value> &vector,
              index_type index) noexcept -> bool
  {
    if constexpr (std::signed_integral<index_type>)
    {
      if (index < 0)
      {
        return false;
      }
    }

    return static_cast<std::size_t>(index) < vector.size();
  }

  template <std::integral value_type, std::integral index_type>
  [[nodiscard]] constexpr auto valid_index(const Range<value_type> &range,
                                           index_type index) noexcept -> bool
  {
    if constexpr (std::signed_integral<index_type>)
    {
      if (index < 0)
      {
        return false;
      }
    }

    return static_cast<std::size_t>(index) < range.size();
  }

} // namespace cljonic
// End cljonic-core-valid-index.hpp

namespace cljonic
{

  /** \anchor Core_Get
   * \b get returns the logical element at \p index when the index is valid.
   * When the index is invalid, the default element is returned.
   *
   ~~~~~{.cpp}
   #include "cljonic.hpp"
   using namespace cljonic;

   int main() {
     const auto values = Vector<int, 4>{10, 20};

     const auto v0 = get(values, 0U);     // 10
     const auto v1 = get(values, 2U);     // 0
     const auto v2 = get(values, 2U, 99); // 99

     return (v0 == 10 && v1 == 0 && v2 == 99) ? 0 : 1;
   }
   ~~~~~
   */
  template <typename element_type, std::size_t capacity_value,
            std::integral index_type>
  [[nodiscard]] constexpr auto
  get(const Vector<element_type, capacity_value> &vector,
      index_type index) noexcept -> element_type
  {
    return valid_index(vector, index) ? vector(index) : element_type{};
  }

  /** \anchor Core_Get_Fallback
   * \b get returns the logical element at \p index when the index is valid.
   * When the index is invalid, \p fallback is returned.
   */
  template <typename element_type, std::size_t capacity_value,
            std::integral index_type>
  [[nodiscard]] constexpr auto
  get(const Vector<element_type, capacity_value> &vector, index_type index,
      const element_type &fallback) noexcept -> element_type
  {
    return valid_index(vector, index) ? vector(index) : fallback;
  }

} // namespace cljonic
// End cljonic-core-get.hpp

namespace cljonic {

namespace core {} // namespace core

} // namespace cljonic

#endif // CLJONIC_CORE_HPP
// End cljonic-core.hpp
