// Generated by scripts/amalgamate.py. Do not edit.

// Begin cljonic-core.hpp
#ifndef CLJONIC_CORE_HPP
#define CLJONIC_CORE_HPP

// Begin cljonic-config.hpp
#pragma once

#if !defined(CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT)
#define CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT 1000
#endif

#define CLJONIC_STRINGIFY_INNER(x) #x
#define CLJONIC_STRINGIFY(x) CLJONIC_STRINGIFY_INNER(x)// End cljonic-config.hpp

/** \mainpage
 * \b cljonic is a \b header-only C++ library designed to allow an \b embedded
 * \b systems C++ developer to program in a \b Functional \b Programming \b
 * Style using a set of functions \b similar in \b name and \b function to \b
 * Clojure. To address the embedded systems focus, \b cljonic \b DOES \b NOT use
 * the heap or exceptions, and uses \b Modern \b C++ features to \b protect , \b
 * guide , and \b teach C++ developers. Finally, \b cljonic is a library that
 * includes unit tests with nearly <b>100% coverage</b>, and is designed to be
 * efficiently maintained.
 *
 * The motivation for \b cljonic comes from observations made about the
 * pragmatic use of C++ for embedded systems software development, the
 * progression of the C++ language (e.g., C++11, C++14, C++17, C++20, C++23),
 * and the counsel of software development "experts", in many different
 * programming languages, that <b>a functional programming style should be
 * eagerly embraced by all developers</b>.
 *
 * Many embedded systems C++ developers are <b>not academic programming language
 * experts</b> with in-depth knowledge of every C++ feature, and many <b>may not
 * have time</b> to follow the progression of the language.  Rather, many
 * embedded systems C++ developers have <b>strong hardware backgrounds</B>, and
 * <B>know a pragmatic specific subset of C++</B> that is often sufficient to
 * deliver reasonably good software in a predictable amount of time, though this
 * is often <b>not optimized for minimal long term cost of ownership</b>.
 * Generally speaking, many C++ developers use a subset of the \b C programming
 * language with some of C++'s <b>Object Oriented</b> capabilities.  This begs a
 * question:
 *
 * <b>Is there a pragmatic subset of Modern C++ that enables embedded systems
 * developers to produce higher-quality, more efficient, and more maintainable
 * code?</b>
 *
 * Changes to C++ have provided valuable capabilities that are time consuming to
 * master, hence it is both <b> valuable to development organizations</b> for
 * their developers to use modern C++ capabilities, and <b> too expensive to
 * train</b> all of their developers to be experts in their use.  This, too,
 * begs a question:
 *
 * <b>Can one or two embedded systems software developers cost-effectively
 * introduce modern C++ capabilities to the entire team?</b>
 *
 * In this post:
 *
 *     https://www.gamedeveloper.com/programming/in-depth-functional-programming-in-c-
 *
 * the author makes the following statements:
 *
 * <b>"A large fraction of the flaws in software development are due to
 * programmers not fully understanding all the possible states their code may
 * execute in. In a multithreaded environment, the lack of understanding and the
 *  resulting problems are greatly amplified, almost to the point of panic if
 * you are paying attention. Programming in a functional style makes the state
 * presented to your code explicit, which makes it much easier to reason about
 *  [(i.e., Fewer mistakes, and less debugging)], and, in a completely pure
 * system, makes thread race conditions impossible."
 *
 * "No matter what language you work in, programming in a functional style
 * provides benefits. You should do it whenever it is convenient, and you should
 * think hard about the decision when it isn't convenient."</b>
 *
 * \b cljonic is a \b header-only library that utilizes \b Modern \b C++
 * capabilities to provide a functional style C++ \b Clojure subset to \b
 * embedded \b systems developers, promotes the \b predictable \b development of
 * \b higher \b quality code \b faster, and can be \b cost-effectively \b
 * maintained over time.
 *
 * \anchor Core_Cheatsheet
 * ___
 * # Cheatsheet
 *
 * ## Aliases
 *
 * | Namespace | "using" C++ Statement |
 * |-----------|-------------------------|
 * | \ref Namespace_Core "core" | using **core** = cljonic::core; |
 * | \ref Namespace_Set "set" | using **set** = cljonic::set; |
 * | \ref Namespace_String "string" | using **string** = cljonic::string; |
 *
 * ## Collection Types
 *
 * - \ref Vector "cljonic::Vector"
 *
 * ## Planned Core Functions
 *
 * ### Composition
 *
 * - \ref Core_Partial "Partial"
 *
 * ### Control
 *
 * - \ref Core_DoSeq "DoSeq", \ref Core_DoTimes "DoTimes", \ref Core_If "If",
 * \ref Core_Unless "Unless", \ref Core_When "When", \ref Core_WhenNot "WhenNot"
 *
 * ### Predicate
 *
 * - \ref Core_Compare "Compare"
 * - \ref Core_EQ "EQ"
 * - \ref Core_GE "GE", \ref Core_GT "GT"
 * - \ref Core_IsAlpha "IsAlpha", \ref Core_IsAlphanumeric "IsAlphanumeric",
 * \ref Core_IsBlank "IsBlank", \ref Core_IsControl "IsControl", \ref
 * Core_IsDigit "IsDigit", \ref Core_IsEven "IsEven", \ref Core_IsGraphical
 * "IsGraphical", \ref Core_IsHexDigit "IsHexDigit", \ref Core_IsLowercase
 * "IsLowercase", \ref Core_IsNatural "IsNatural", \ref Core_IsNegative
 * "IsNegative", \ref Core_IsOdd "IsOdd", \ref Core_IsPositive "IsPositive",
 * \ref Core_IsPrintable "IsPrintable", \ref Core_IsPunctuation "IsPunctuation",
 * \ref Core_IsSpace "IsSpace", \ref Core_IsUppercase "IsUppercase", \ref
 * Core_IsZero "IsZero"
 * - \ref Core_LE "LE", \ref Core_LT "LT"
 * - \ref Core_NE "NE"
 *
 * ### Primitive
 *
 * - \ref Core_Abs "Abs", \ref Core_Add "Add"
 * - \ref Core_Char "Char", \ref Core_Combinations "Combinations", \ref
 * Core_CString "CString"
 * - \ref Core_Dec "Dec", \ref Core_Div "Div"
 * - \ref Core_Factorial "Factorial"
 * - \ref Core_Inc "Inc"
 * - \ref Core_Lowercase "Lowercase"
 * - \ref Core_Max "Max", \ref Core_Min "Min", \ref Core_Mod "Mod", \ref
 * Core_Mul "Mul"
 * - \ref Core_Ord "Ord"
 * - \ref Core_Permutations "Permutations"
 * - \ref Core_Sub "Sub",
 * - \ref Core_Uppercase "Uppercase"
 *
 * ### Seq (i.e., Sequence: Vector)
 *
 * The Vector type is the initial public surface. Free-function collection
 * operations are introduced only when their requirements are approved.
 * - \ref Core_Dedupe "Dedupe", \ref Core_DedupeBy "DedupeBy", \ref
 * Core_DefaultElement "DefaultElement", \ref Core_DefaultElement_M
 * "DefaultElement_M", \ref Core_Different "Different", \ref Core_Distinct
 * "Distinct", \ref Core_DistinctBy "DistinctBy", \ref Core_Drop "Drop", \ref
 * Core_DropLast "DropLast", \ref Core_DropWhile "DropWhile"
 * - \ref Core_Empty_M "Empty_M", \ref Core_Equal "Equal", \ref Core_EqualBy
 * "EqualBy", \ref Core_Every "Every"
 * - \ref Core_Filter "Filter", \ref Core_First "First", \ref Core_Flatten
 * "Flatten", \ref Core_FlattenSize "FlattenSize", \ref Core_Frequencies
 * "Frequencies", \ref Core_FrequenciesBy "FrequenciesBy"
 * - \ref Core_Identical "Identical", \ref Core_Identity "Identity", \ref
 * Core_IndexOf "IndexOf", \ref Core_IndexOfBy "IndexOfBy", \ref Core_Interleave
 * "Interleave", \ref Core_Interpose "Interpose", \ref Core_IsDistinct
 * "IsDistinct", \ref Core_IsDistinctBy "IsDistinctBy", \ref Core_IsEmpty
 * "IsEmpty", \ref Core_IsFull "IsFull", \ref Core_Iterate "Iterate"
 * - \ref Core_Juxt "Juxt"
 * - \ref Core_Last "Last", \ref Core_LastIndexOf "LastIndexOf", \ref
 * Core_LastIndexOfBy "LastIndexOfBy"
 * - \ref Core_Map "Map", \ref Core_Max "Max", \ref Core_MaxBy "MaxBy", \ref
 * Core_Min "Min", \ref Core_MinBy "MinBy"
 * - \ref Core_NotAny "NotAny", \ref Core_NotEvery "NotEvery", \ref Core_Nth
 * "Nth", \ref Core_Nth_M "Nth_M"
 * - \ref Core_Partition "Partition", \ref Core_PartitionAll "PartitionAll",
 * \ref Core_PartitionBy "PartitionBy"
 * - \ref Core_Reduce "Reduce", \ref Core_Reductions "Reductions", \ref
 * Core_Remove "Remove", \ref Core_Replace "Replace", \ref Core_Reverse
 * "Reverse"
 * - \ref Core_Second "Second", \ref Core_Seq "Seq", \ref Core_Size "Size", \ref
 * Core_Some "Some", \ref Core_Sort "Sort", \ref Core_SortBy "SortBy", \ref
 * Core_SplitAt "SplitAt", \ref Core_SplitWith "SplitWith", \ref Core_Subs
 * "Subs"
 * - \ref Core_Take "Take", \ref Core_TakeLast "TakeLast", \ref Core_TakeNth
 * "TakeNth", \ref Core_TakeWhile "TakeWhile"
 *
 * ## Set Functions
 *
 * - \ref Set_Conj "Conj", \ref Set_ConjBy "ConjBy", \ref Set_Contains
 * "Contains", \ref Set_ContainsBy "ContainsBy"
 * - \ref Set_Difference "Difference", \ref Set_DifferenceBy "DifferenceBy",
 * \ref Set_Disj "Disj", \ref Set_DisjBy "DisjBy"
 * - \ref Set_IndexOf "IndexOf", \ref Set_IndexOfBy "IndexOfBy", \ref
 * Set_Intersection "Intersection", \ref Set_IntersectionBy "IntersectionBy"
 * - \ref Set_ToSet "ToSet", \ref Set_ToSetBy "ToSetBy"
 * - \ref Set_Union "Union", \ref Set_UnionBy "UnionBy"
 *
 * ## String Functions
 *
 * - \ref String_Capitalize "Capitalize", \ref String_Compare "Compare", \ref
 * String_Concat "Concat"
 * - \ref String_EndsWith "EndsWith"
 * - \ref String_FloatToString "FloatToString", \ref String_Format "Format"
 * - \ref String_Includes "Includes", \ref String_IndexOf "IndexOf", \ref
 * String_Interpose "Interpose", \ref String_IntToString "IntToString", \ref
 * String_IntToStringHex "IntToStringHex", \ref String_IsBlank "IsBlank"
 * - \ref String_LastIndexOf "LastIndexOf", \ref String_Lowercase "Lowercase"
 * - \ref String_Partition "Partition", \ref String_PartitionAll "PartitionAll",
 * \ref String_PartitionBy "PartitionBy"
 * - \ref String_Replace "Replace", \ref String_ReplaceFirst "ReplaceFirst"
 * - \ref String_Split "Split", \ref String_SplitCount "SplitCount", \ref
 * String_SplitLine "SplitLine", \ref String_StartsWith "StartsWith", \ref
 * String_StrLen "StrLen", \ref String_StrOfChar "StrOfChar", \ref
 * String_StrToFloat "StrToFloat", \ref String_StrToIntDecimal
 * "StrToIntDecimal", \ref String_StrToIntHex "StrToIntHex", \ref String_Subs
 * "Subs"
 * - \ref String_Trim "Trim", \ref String_TrimLeft "TrimLeft", \ref
 * String_TrimNewLine "TrimNewLine", \ref String_TrimRight "TrimRight"
 * - \ref String_Uppercase "Uppercase"
 */

/** \anchor Namespace_Core
 * The \b Core namespace provides the vast majority of \b cljonic functions.
 * The current Core surface starts with the Vector collection. Free-function
 * collection operations are planned for later requirements modules.
 */

// Begin cljonic-assoc.hpp
#ifndef CLJONIC_ASSOC_HPP
#define CLJONIC_ASSOC_HPP

// Begin cljonic-concepts.hpp
#pragma once

#include <concepts>
#include <cstddef>

namespace cljonic::concepts {

/** Requires that \p value_type is default-initializable and copyable - the
 * minimum contract for current Vector element storage semantics.
 */
template <typename value_type>
concept VectorElement =
    std::default_initializable<value_type> && std::copyable<value_type>;

/** Requires that Vector storage can be initialized and assigned without
 * throwing.
 */
template <typename value_type>
concept NothrowVectorElement =
    VectorElement<value_type> &&
    requires(value_type value, const value_type &other) {
      { value_type{} } noexcept;
      { value_type{other} } noexcept;
      { value = other } noexcept;
    };

/** Requires that an argument is implicitly convertible to and can construct a
 * Vector element without throwing.
 */
template <typename value_type, typename argument_type>
concept NothrowElementConstruction =
    std::convertible_to<argument_type, value_type> &&
    requires(argument_type argument) {
      { argument_type{argument} } noexcept;
      { value_type{argument} } noexcept;
    };

} // namespace cljonic::concepts
// End cljonic-concepts.hpp
#include <utility>

namespace cljonic {

/** \anchor Assoc
 * \brief Associates a key and value in an associative collection or index in a
 * vector.
 *
 * \b Examples
 * ~~~~~{.cpp}
 * #include <cljonic.hpp>
 *
 * int main() {
 *   using namespace cljonic;
 *
 *   constexpr auto m = assoc(Map<int, int, 4>{}, 1, 100);
 *   static_assert(m.contains(1));
 *   static_assert(m(1) == 100);
 *
 *   return 0;
 * }
 * ~~~~~
 */
template <typename C, typename K, typename V>
[[nodiscard]] constexpr auto assoc(const C &collection, const K &key,
                                   const V &value) noexcept {
  return collection.assoc(key, value);
}

} // namespace cljonic

#endif // CLJONIC_ASSOC_HPP
// End cljonic-assoc.hpp
// Begin cljonic-can-assoc.hpp
#ifndef CLJONIC_CAN_ASSOC_HPP
#define CLJONIC_CAN_ASSOC_HPP

#include <utility>

namespace cljonic {

/** \anchor CanAssoc
 * \brief Checks if assoc can succeed without capacity overflow.
 *
 * \b Examples
 * ~~~~~{.cpp}
 * #include <cljonic.hpp>
 *
 * int main() {
 *   using namespace cljonic;
 *
 *   constexpr Map<int, int, 4> m{};
 *   static_assert(can_assoc(m, 1, 100));
 *
 *   return 0;
 * }
 * ~~~~~
 */
template <typename C, typename K, typename V>
[[nodiscard]] constexpr auto can_assoc(const C &collection, const K &key,
                                       const V &value) noexcept -> bool {
  return collection.can_assoc(key, value);
}

} // namespace cljonic

#endif // CLJONIC_CAN_ASSOC_HPP
// End cljonic-can-assoc.hpp
// Begin cljonic-can-conj.hpp
#ifndef CLJONIC_CAN_CONJ_HPP
#define CLJONIC_CAN_CONJ_HPP

#include <utility>

namespace cljonic {

/** \anchor CanConj
 * \brief Checks if conj can succeed without capacity overflow.
 *
 * \b Examples
 * ~~~~~{.cpp}
 * #include <cljonic.hpp>
 *
 * int main() {
 *   using namespace cljonic;
 *
 *   constexpr Queue<int, 4> q{};
 *   static_assert(can_conj(q));
 *
 *   constexpr Set<int, 4> s{};
 *   static_assert(can_conj(s, 1));
 *
 *   return 0;
 * }
 * ~~~~~
 */
template <typename C, typename... Args>
[[nodiscard]] constexpr auto can_conj(const C &collection,
                                      Args &&...args) noexcept -> bool {
  return collection.can_conj(std::forward<Args>(args)...);
}

} // namespace cljonic

#endif // CLJONIC_CAN_CONJ_HPP
// End cljonic-can-conj.hpp
// Begin cljonic-conj.hpp
#ifndef CLJONIC_CONJ_HPP
#define CLJONIC_CONJ_HPP

#include <utility>

namespace cljonic {

/** \anchor Conj
 * \brief Adds an element to a collection according to its type conventions.
 *
 * \b Examples
 * ~~~~~{.cpp}
 * #include <cljonic.hpp>
 *
 * int main() {
 *   using namespace cljonic;
 *
 *   constexpr auto q = conj(Queue<int, 4>{}, 10);
 *   constexpr auto s = conj(Set<int, 4>{}, 20);
 *
 *   static_assert(peek(q) == 10);
 *   static_assert(s.contains(20));
 *
 *   return 0;
 * }
 * ~~~~~
 */
template <typename C, typename T>
[[nodiscard]] constexpr auto conj(const C &collection,
                                  const T &value) noexcept {
  return collection.conj(value);
}

} // namespace cljonic

#endif // CLJONIC_CONJ_HPP
// End cljonic-conj.hpp
// Begin cljonic-core-collection-maximum-element-count.hpp
#pragma once

#include <cstddef>


namespace cljonic {

/** \anchor CollectionMaximumElementCountValue
 * \b CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT_VALUE is a constexpr constant
 * that captures the configured synthesis ceiling for bounded cljonic
 * collections and semantically infinite producers. This type-safe constant
 * can be used in compile-time expressions, static assertions, and constexpr
 * functions while remaining fully overridable via the
 * CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT macro.
 */
constexpr std::size_t CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT_VALUE =
    CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT;

} // namespace cljonic
// End cljonic-core-collection-maximum-element-count.hpp
// Begin cljonic-disj.hpp
#ifndef CLJONIC_DISJ_HPP
#define CLJONIC_DISJ_HPP

#include <utility>

namespace cljonic {

/** \anchor Disj
 * \brief Disjoins an element from a set.
 *
 * \b Examples
 * ~~~~~{.cpp}
 * #include <cljonic.hpp>
 *
 * int main() {
 *   using namespace cljonic;
 *
 *   constexpr auto s0 = conj(Set<int, 4>{}, 42);
 *   constexpr auto s1 = disj(s0, 42);
 *   static_assert(!s1.contains(42));
 *
 *   return 0;
 * }
 * ~~~~~
 */
template <typename C, typename T>
[[nodiscard]] constexpr auto disj(const C &collection,
                                  const T &value) noexcept {
  return collection.disj(value);
}

} // namespace cljonic

#endif // CLJONIC_DISJ_HPP
// End cljonic-disj.hpp
// Begin cljonic-dissoc.hpp
#ifndef CLJONIC_DISSOC_HPP
#define CLJONIC_DISSOC_HPP

#include <utility>

namespace cljonic {

/** \anchor Dissoc
 * \brief Disassociates a key from a map.
 *
 * \b Examples
 * ~~~~~{.cpp}
 * #include <cljonic.hpp>
 *
 * int main() {
 *   using namespace cljonic;
 *
 *   constexpr auto m0 = assoc(Map<int, int, 4>{}, 1, 100);
 *   constexpr auto m1 = dissoc(m0, 1);
 *   static_assert(!m1.contains(1));
 *
 *   return 0;
 * }
 * ~~~~~
 */
template <typename C, typename K>
[[nodiscard]] constexpr auto dissoc(const C &collection,
                                    const K &key) noexcept {
  return collection.dissoc(key);
}

} // namespace cljonic

#endif // CLJONIC_DISSOC_HPP
// End cljonic-dissoc.hpp
// Begin cljonic-map.hpp
#pragma once

#include <array>
#include <concepts>
#include <cstddef>
#include <utility>

// Begin cljonic-map-entry.hpp
#pragma once

#include <concepts>
#include <cstddef>

namespace cljonic {

/** \anchor MapEntry
 * \b MapEntry is a value-semantic pair representing a single key-value
 * association.
 */
template <typename KeyType, typename ValueType> struct MapEntry {
  KeyType key{};
  ValueType value{};

  [[nodiscard]] constexpr auto
  operator==(const MapEntry &other) const noexcept -> bool {
    return key == other.key && value == other.value;
  }

  template <std::integral IndexType>
  [[nodiscard]] constexpr auto
  valid_index(IndexType index) const noexcept -> bool {
    if constexpr (std::signed_integral<IndexType>) {
      if (index < 0) {
        return false;
      }
    }
    return static_cast<std::size_t>(index) < 2U;
  }
};

} // namespace cljonic
// End cljonic-map-entry.hpp

namespace cljonic {

/** \anchor Map
 * \b Map is a fixed-capacity associative collection backed by contiguous array
 * storage and linear scan lookup with copy-on-modify updates.
 */
template <concepts::VectorElement KeyType, concepts::VectorElement ValueType,
          std::size_t CapacityValue>
class Map {
public:
  using key_type = KeyType;
  using mapped_type = ValueType;
  using value_type = MapEntry<KeyType, ValueType>;

  static_assert(concepts::NothrowVectorElement<KeyType>,
                "Map key type operations must not throw");
  static_assert(concepts::NothrowVectorElement<ValueType>,
                "Map value type operations must not throw");
  static_assert(
      CapacityValue <= cljonic::CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT_VALUE,
      "Map capacity exceeds CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT");

  constexpr Map() noexcept : entries_{}, logical_size_{0} {}

  [[nodiscard]] static constexpr auto capacity() noexcept -> std::size_t {
    return CapacityValue;
  }

  [[nodiscard]] constexpr auto size() const noexcept -> std::size_t {
    return logical_size_;
  }

  [[nodiscard]] constexpr auto empty() const noexcept -> bool {
    return logical_size_ == 0U;
  }

  [[nodiscard]] constexpr auto
  contains(const KeyType &key) const noexcept -> bool {
    return find_index(key) < logical_size_;
  }

  [[nodiscard]] constexpr auto
  operator()(const KeyType &key) const noexcept -> ValueType {
    const auto idx = find_index(key);
    return (idx < logical_size_) ? entries_[idx].value : ValueType{};
  }

  [[nodiscard]] constexpr auto
  operator()(const KeyType &key,
             const ValueType &fallback) const noexcept -> ValueType {
    const auto idx = find_index(key);
    return (idx < logical_size_) ? entries_[idx].value : fallback;
  }

  [[nodiscard]] constexpr auto
  can_assoc(const KeyType &key) const noexcept -> bool {
    return contains(key) || (logical_size_ < CapacityValue);
  }

  [[nodiscard]] constexpr auto
  can_assoc(const KeyType &key,
            const ValueType & /*value*/) const noexcept -> bool {
    return can_assoc(key);
  }

  [[nodiscard]] constexpr auto
  assoc(const KeyType &key, const ValueType &value) const noexcept -> Map {
    Map result = *this;
    const auto idx = result.find_index(key);
    if (idx < result.logical_size_) {
      result.entries_[idx].value = value;
    } else if (result.logical_size_ < CapacityValue) {
      result.entries_[result.logical_size_] = value_type{key, value};
      ++result.logical_size_;
    }
    return result;
  }

  [[nodiscard]] constexpr auto
  dissoc(const KeyType &key) const noexcept -> Map {
    Map result = *this;
    const auto idx = result.find_index(key);
    if (idx < result.logical_size_) {
      if (idx + 1U < result.logical_size_) {
        result.entries_[idx] = result.entries_[result.logical_size_ - 1U];
      }
      --result.logical_size_;
    }
    return result;
  }

private:
  [[nodiscard]] constexpr auto
  find_index(const KeyType &key) const noexcept -> std::size_t {
    for (std::size_t i = 0; i < logical_size_; ++i) {
      if (entries_[i].key == key) {
        return i;
      }
    }
    return logical_size_;
  }

  std::array<value_type, CapacityValue> entries_{};
  std::size_t logical_size_{0};
};

} // namespace cljonic
// End cljonic-map.hpp
// Begin cljonic-peek.hpp
#ifndef CLJONIC_PEEK_HPP
#define CLJONIC_PEEK_HPP

#include <utility>

namespace cljonic {

/** \anchor Peek
 * \brief Observes the accessible element without removal.
 *
 * \b Examples
 * ~~~~~{.cpp}
 * #include <cljonic.hpp>
 *
 * int main() {
 *   using namespace cljonic;
 *
 *   constexpr auto q = conj(Queue<int, 4>{}, 99);
 *   static_assert(peek(q) == 99);
 *
 *   return 0;
 * }
 * ~~~~~
 */
template <typename C>
[[nodiscard]] constexpr auto peek(const C &collection) noexcept {
  return collection.peek();
}

} // namespace cljonic

#endif // CLJONIC_PEEK_HPP
// End cljonic-peek.hpp
// Begin cljonic-pop.hpp
#ifndef CLJONIC_POP_HPP
#define CLJONIC_POP_HPP

#include <utility>

namespace cljonic {

/** \anchor Pop
 * \brief Yields an updated collection with the accessible element removed.
 *
 * \b Examples
 * ~~~~~{.cpp}
 * #include <cljonic.hpp>
 *
 * int main() {
 *   using namespace cljonic;
 *
 *   constexpr auto q0 = conj(conj(Queue<int, 4>{}, 1), 2);
 *   constexpr auto q1 = pop(q0);
 *   static_assert(peek(q1) == 2);
 *
 *   return 0;
 * }
 * ~~~~~
 */
template <typename C>
[[nodiscard]] constexpr auto pop(const C &collection) noexcept {
  return collection.pop();
}

} // namespace cljonic

#endif // CLJONIC_POP_HPP
// End cljonic-pop.hpp
// Begin cljonic-queue.hpp
#pragma once

#include <array>
#include <concepts>
#include <cstddef>
#include <utility>


namespace cljonic {

/** \anchor Queue
 * \b Queue is a fixed-capacity FIFO sequence collection backed by contiguous
 * array storage with copy-on-modify semantics.
 */
template <concepts::VectorElement T, std::size_t CapacityValue> class Queue {
public:
  using value_type = T;

  static_assert(concepts::NothrowVectorElement<T>,
                "Queue element type operations must not throw");
  static_assert(
      CapacityValue <= cljonic::CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT_VALUE,
      "Queue capacity exceeds CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT");

  constexpr Queue() noexcept : elements_{}, head_{0}, logical_size_{0} {}

  [[nodiscard]] static constexpr auto capacity() noexcept -> std::size_t {
    return CapacityValue;
  }

  [[nodiscard]] constexpr auto size() const noexcept -> std::size_t {
    return logical_size_;
  }

  [[nodiscard]] constexpr auto empty() const noexcept -> bool {
    return logical_size_ == 0U;
  }

  /** Returns true when there is room for at least one more element. */
  [[nodiscard]] constexpr auto can_conj() const noexcept -> bool {
    return logical_size_ < CapacityValue;
  }

  /** Adds an element to the back of a copy of the queue (enqueue). Returns an
   * unchanged copy when full. */
  [[nodiscard]] constexpr auto conj(const T &element) const noexcept -> Queue {
    Queue result = *this;
    if (result.logical_size_ < CapacityValue) {
      const auto tail = (result.head_ + result.logical_size_) % CapacityValue;
      result.elements_[tail] = element;
      ++result.logical_size_;
    }
    return result;
  }

  /** Peeks at the front element without removing it. Returns
   * default-constructed value when empty. */
  [[nodiscard]] constexpr auto peek() const noexcept -> T {
    return (logical_size_ > 0) ? elements_[head_] : T{};
  }

  /** Removes the front element from a copy of the queue (dequeue). Returns an
   * unchanged copy when empty. */
  [[nodiscard]] constexpr auto pop() const noexcept -> Queue {
    Queue result = *this;
    if (result.logical_size_ > 0) {
      result.head_ = (result.head_ + 1) % CapacityValue;
      --result.logical_size_;
    }
    return result;
  }

private:
  std::array<value_type, CapacityValue> elements_{};
  std::size_t head_{0};
  std::size_t logical_size_{0};
};

} // namespace cljonic
// End cljonic-queue.hpp
// Begin cljonic-set.hpp
#ifndef CLJONIC_SET_HPP
#define CLJONIC_SET_HPP

#include <array>
#include <concepts>
#include <cstddef>
#include <utility>


namespace cljonic {

/** \anchor Set
 * \b Set is a fixed-capacity associative sequence collection backed by
 * contiguous array storage with linear-scan lookup and copy-on-modify
 * semantics.
 */
template <concepts::VectorElement T, std::size_t CapacityValue> class Set {
public:
  using value_type = T;

  static_assert(concepts::NothrowVectorElement<T>,
                "Set element type operations must not throw");
  static_assert(
      CapacityValue <= cljonic::CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT_VALUE,
      "Set capacity exceeds CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT");

  constexpr Set() noexcept : elements_{}, logical_size_{0} {}

  [[nodiscard]] static constexpr auto capacity() noexcept -> std::size_t {
    return CapacityValue;
  }

  [[nodiscard]] constexpr auto size() const noexcept -> std::size_t {
    return logical_size_;
  }

  [[nodiscard]] constexpr auto count() const noexcept -> std::size_t {
    return logical_size_;
  }

  [[nodiscard]] constexpr auto empty() const noexcept -> bool {
    return logical_size_ == 0U;
  }

  [[nodiscard]] constexpr auto
  contains(const T &element) const noexcept -> bool {
    return find_index(element) < logical_size_;
  }

  /** Returns the stored element value when present; otherwise returns a
   * default-constructed value. */
  [[nodiscard]] constexpr auto
  operator()(const T &element) const noexcept -> T {
    const auto idx = find_index(element);
    return (idx < logical_size_) ? elements_[idx] : T{};
  }

  /** Returns the stored element value when present; otherwise returns the
   * supplied fallback. */
  [[nodiscard]] constexpr auto
  operator()(const T &element, const T &fallback) const noexcept -> T {
    const auto idx = find_index(element);
    return (idx < logical_size_) ? elements_[idx] : fallback;
  }

  /** Returns true when the element is already present or the set has room for
   * one more. */
  [[nodiscard]] constexpr auto
  can_conj(const T &element) const noexcept -> bool {
    return contains(element) || (logical_size_ < CapacityValue);
  }

  /** Adds an element to a copy of the set. If the element is already present or
   * capacity is full, returns an unchanged copy. */
  [[nodiscard]] constexpr auto conj(const T &element) const noexcept -> Set {
    Set result = *this;
    if (!result.contains(element) && result.logical_size_ < CapacityValue) {
      result.elements_[result.logical_size_] = element;
      ++result.logical_size_;
    }
    return result;
  }

  /** Removes an element via swap-and-remove if present; always returns a valid
   * copy. */
  [[nodiscard]] constexpr auto disj(const T &element) const noexcept -> Set {
    Set result = *this;
    const auto idx = result.find_index(element);
    if (idx < result.logical_size_) {
      if (idx + 1U < result.logical_size_) {
        result.elements_[idx] = result.elements_[result.logical_size_ - 1U];
      }
      --result.logical_size_;
    }
    return result;
  }

private:
  /** Returns `logical_size_` when the element is absent. */
  [[nodiscard]] constexpr auto
  find_index(const T &element) const noexcept -> std::size_t {
    for (std::size_t i = 0; i < logical_size_; ++i) {
      if (elements_[i] == element) {
        return i;
      }
    }
    return logical_size_;
  }

  std::array<value_type, CapacityValue> elements_{};
  std::size_t logical_size_{0};
};

} // namespace cljonic

#endif // CLJONIC_SET_HPP
// End cljonic-set.hpp
// Begin cljonic-string.hpp
#pragma once

#include <array>
#include <concepts>
#include <cstddef>
#include <utility>


namespace cljonic {

/** \anchor String
 * \b String is a fixed-capacity ASCII string backed by contiguous array storage
 * with automatic null termination and copy-on-modify semantics.
 */
template <std::size_t CapacityValue> class String {
public:
  using value_type = char;

  static_assert(
      CapacityValue <= cljonic::CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT_VALUE,
      "String capacity exceeds CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT");

  constexpr String() noexcept : data_{}, logical_size_{0} { data_[0] = '\0'; }

  /** Construct from character array literal. Capacity must accommodate N-1
   * chars plus null terminator. */
  template <std::size_t N>
  constexpr String(const char (&arr)[N]) noexcept : data_{}, logical_size_{0} {
    static_assert(N - 1U <= CapacityValue,
                  "String literal too long for capacity");
    logical_size_ = N - 1U;
    for (std::size_t i = 0; i < logical_size_; ++i) {
      data_[i] = arr[i];
    }
    data_[logical_size_] = '\0';
  }

  [[nodiscard]] static constexpr auto capacity() noexcept -> std::size_t {
    return CapacityValue;
  }

  [[nodiscard]] constexpr auto size() const noexcept -> std::size_t {
    return logical_size_;
  }

  [[nodiscard]] constexpr auto empty() const noexcept -> bool {
    return logical_size_ == 0U;
  }

  /** Returns true when index falls within logical bounds (not counting null
   * terminator). */
  [[nodiscard]] constexpr auto valid(std::size_t index) const noexcept -> bool {
    return index < logical_size_;
  }

  /** Index access: returns '\\0' for out-of-bounds indices. */
  [[nodiscard]] constexpr auto
  operator[](std::size_t index) const noexcept -> char {
    return (index < logical_size_) ? data_[index] : '\0';
  }

  /** Callable index access returning default-constructed char ('\\0') on
   * invalid index. */
  [[nodiscard]] constexpr auto
  operator()(std::size_t index) const noexcept -> char {
    return (index < logical_size_) ? data_[index] : '\0';
  }

  /** Callable index access with custom fallback value on invalid index. */
  [[nodiscard]] constexpr auto
  operator()(std::size_t index, char fallback) const noexcept -> char {
    return (index < logical_size_) ? data_[index] : fallback;
  }

  /** Returns a fresh String with the character at index replaced. Out-of-bounds
   * indices leave copy unchanged. */
  [[nodiscard]] constexpr auto put(std::size_t index,
                                   char c) const noexcept -> String {
    String result = *this;
    if (index < logical_size_) {
      result.data_[index] = c;
    }
    return result;
  }

  /** Appends a character to the end of a copy of the string if room is
   * available. */
  [[nodiscard]] constexpr auto append(char c) const noexcept -> String {
    String result = *this;
    if (result.logical_size_ < CapacityValue) {
      result.data_[result.logical_size_] = c;
      ++result.logical_size_;
      result.data_[result.logical_size_] = '\0';
    }
    return result;
  }

private:
  // Internal array is CapacityValue+1 to hold null terminator
  std::array<char, CapacityValue + 1> data_{};
  std::size_t logical_size_{0};
};

} // namespace cljonic
// End cljonic-string.hpp
// Begin cljonic-vector.hpp
#pragma once

#include <array>
#include <cstddef>
#include <utility>


namespace cljonic {

// Spec obligations: Vector and its invariants are implemented by this type
// and covered by the corresponding traceable tests.
// entity-fields.Vector
// invariant.Vector.CapacityIsNonNegative
// invariant.Vector.LogicalSizeIsNonNegative
// invariant.Vector.LogicalSizeDoesNotExceedCapacity
// invariant.Vector.SupportsLiteralDeducedConstruction
// invariant.Vector.SupportsEmptyExplicitCapacityConstruction
// invariant.Vector.OversizedInitializerIsCompileTimeFailure
// invariant.Vector.OversizedInitializerDiagnosticIdentifiesCapacity
// invariant.Vector.SupportsIndexedLookup
// invariant.Vector.SupportsIndexedFallbackLookup
// invariant.Vector.InvalidIndexReturnsDefaultElement
// invariant.Vector.InvalidIndexReturnsSuppliedFallback

/** \anchor Vector
 * \b Vector is a CopyOnModifyCollection with fixed-capacity storage.
 * Construction with more initializers than capacity is a compile-time error.
 *
 * This example covers bounded construction and direct member observation.
 *
 ~~~~~{.cpp}
 #include "cljonic.hpp"
 using namespace cljonic;

 struct Pixel {
   int x;
   int y;

   friend constexpr bool operator==(const Pixel &lhs,
                                    const Pixel &rhs) noexcept {
     return lhs.x == rhs.x && lhs.y == rhs.y;
   }
 };

 using Inner = Vector<int, 2>;

 int main() {
   // Compile-time / constexpr demonstration.
   [[maybe_unused]] constexpr auto ints_at_capacity = Vector{1, 2, 3};
   [[maybe_unused]] constexpr auto ints_populated = Vector<int, 4>{1, 2};
   [[maybe_unused]] constexpr auto ints_empty = Vector<int, 4>{};
   [[maybe_unused]] constexpr auto nested_int_vectors =
       Vector{Vector<int, 2>{1, 2}, Vector<int, 2>{3}};
   [[maybe_unused]] constexpr auto nested_alias_vectors =
       Vector{Inner{4, 5}, Inner{6}};

   constexpr auto doubles_populated = Vector<double, 3>{1.5, 2.5};
   constexpr auto pixels_populated = Vector{Pixel{1, 2}, Pixel{3, 4}};
   constexpr Vector<int, 4> values{10, 20};

   static_assert(values(0U) == 10);
   static_assert(values(2U) == 0);
   static_assert(values(2U, 99) == 99);
   static_assert(std::same_as<decltype(doubles_populated(0U)), double>);
   static_assert(pixels_populated(0U).x == 1);
   static_assert(pixels_populated(1U).y == 4);

   // Runtime demonstration.
   auto runtime_values = Vector<int, 4>{7, 9};
   const auto fallback = runtime_values(4U, -1);

   auto runtime_pixels = Vector<Pixel, 4>{Pixel{1, 2}, Pixel{3, 4}};
   const auto pixel_value = runtime_pixels(1U);
   const auto pixel_fallback = runtime_pixels(4U, Pixel{99, 99});

   return (fallback == -1 && pixel_value == Pixel{3, 4} &&
           pixel_fallback == Pixel{99, 99})
              ? 0
              : 1;
 }
 ~~~~~
 */
template <concepts::VectorElement element_type, std::size_t capacity_value>
class Vector {
public:
  using value_type = element_type;

  static_assert(concepts::NothrowVectorElement<element_type>,
                "Vector element storage operations must not throw");

  static_assert(capacity_value <=
                    cljonic::CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT_VALUE,
                "Vector capacity exceeds "
                "CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT=" CLJONIC_STRINGIFY(
                    CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT));

  template <typename... Args>
  constexpr Vector(Args... args) noexcept(
      concepts::NothrowVectorElement<element_type> &&
      (concepts::NothrowElementConstruction<element_type, Args> && ...))
      : storage_{}, logical_size_{0} {
    static_assert(sizeof...(Args) <= capacity_value,
                  "Vector constructor requires initializer count to be less "
                  "than or equal to capacity");
    static_assert(
        (concepts::NothrowElementConstruction<element_type, Args> && ...),
        "Vector constructor requires all arguments to construct "
        "element_type without throwing and be implicitly "
        "convertible to element_type");

    initialize_storage_if_valid(args...);
  }

  [[nodiscard]] static constexpr auto capacity() noexcept -> std::size_t {
    return capacity_value;
  }

  [[nodiscard]] constexpr auto size() const noexcept -> std::size_t {
    return logical_size_;
  }

  template <std::integral index_type>
  [[nodiscard]] constexpr auto
  operator()(index_type index) const noexcept -> value_type {
    return index_is_valid(index) ? storage_[static_cast<std::size_t>(index)]
                                 : value_type{};
  }

  template <std::integral index_type>
  [[nodiscard]] constexpr auto
  operator()(index_type index,
             const value_type &fallback) const noexcept -> value_type {
    return index_is_valid(index) ? storage_[static_cast<std::size_t>(index)]
                                 : fallback;
  }

  template <std::integral index_type>
  [[nodiscard]] constexpr auto
  valid_index(index_type index) const noexcept -> bool {
    return index_is_valid(index);
  }

  [[nodiscard]] constexpr auto empty() const noexcept -> bool {
    return logical_size_ == 0U;
  }

private:
  template <std::integral index_type>
  [[nodiscard]] constexpr auto
  index_is_valid(index_type index) const noexcept -> bool {
    if constexpr (std::signed_integral<index_type>) {
      if (index < 0) {
        return false;
      }
    }

    return static_cast<std::size_t>(index) < logical_size_;
  }

  template <typename... Args>
  static constexpr bool constructor_arguments_valid =
      sizeof...(Args) <= capacity_value &&
      concepts::NothrowVectorElement<element_type> &&
      (concepts::NothrowElementConstruction<element_type, Args> && ...);

  template <typename... Args>
  constexpr void initialize_storage_if_valid(Args... args) noexcept {
    if constexpr (constructor_arguments_valid<Args...>) {
      initialize_storage(std::index_sequence_for<Args...>{}, args...);
      logical_size_ = sizeof...(Args);
    }
  }

  template <std::size_t... Indices, typename... Args>
  constexpr void initialize_storage(std::index_sequence<Indices...>,
                                    Args... args) noexcept {
    ((storage_[Indices] = element_type{args}), ...);
  }

  std::array<value_type, capacity_value> storage_{};
  std::size_t logical_size_ = 0;
};

template <typename First, typename... Rest>
Vector(First, Rest...) -> Vector<First, 1 + sizeof...(Rest)>;

} // namespace cljonic
// End cljonic-vector.hpp

namespace cljonic {

namespace core {} // namespace core

} // namespace cljonic

#endif // CLJONIC_CORE_HPP
// End cljonic-core.hpp
