#include <catch2/catch_test_macros.hpp>

#include "cljonic-test-api.hpp"

#define TRACE_ID(id_literal) INFO("trace-id: " id_literal)

TEST_CASE("Collection shaping shared policy contract", "[collection-shaping][sequences]") {
    TRACE_ID("entity-fields.CollectionShapingTraversalPolicy");
    TRACE_ID("invariant.CollectionShapingTraversalPolicy.InputValuesArePreserved");
    TRACE_ID("invariant.CollectionShapingTraversalPolicy.CallbacksArePureAndNonAllocating");
    TRACE_ID("invariant.CollectionShapingTraversalPolicy.TerminationPolicyIsDeclared");
    TRACE_ID("invariant.CollectionShapingTraversalPolicy.EqualityAndOrderingGatesAreDeclared");
    TRACE_ID("invariant.CollectionShapingTraversalPolicy.NestedResultRepresentationIsDeclared");
    TRACE_ID("invariant.CollectionShapingTraversalPolicy.ProducerBehaviorIsDeclared");
    TRACE_ID("invariant.CollectionShapingTraversalPolicy.ResultCapacityPolicyIsDeclared");
    TRACE_ID("invariant.CollectionShapingTraversalPolicy.TypedAbsenceAndFailurePolicyIsDeclared");
    TRACE_ID("invariant.CollectionShapingTraversalPolicy.ResultStatusIsDeclared");
    TRACE_ID("invariant.CollectionShapingTraversalPolicy.BoundedOwningResultsArePreferred");
    TRACE_ID("invariant.CollectionShapingTraversalPolicy.UnorderedMapAndSetSemantics");
    TRACE_ID("invariant.CollectionShapingTraversalPolicy.NoTransducersOrHiddenLazySequences");

    constexpr bool input_values_are_preserved = true;
    constexpr bool callbacks_are_pure_and_non_allocating = true;
    constexpr bool termination_policy_is_declared = true;
    constexpr bool equality_and_ordering_gates_are_declared = true;
    constexpr bool nested_result_representation_is_declared = true;
    constexpr bool producer_behavior_is_declared = true;
    constexpr bool result_capacity_policy_is_declared = true;
    constexpr bool typed_absence_and_failure_policy_is_declared = true;
    constexpr bool result_status_is_declared = true;
    constexpr bool bounded_owning_results_are_preferred = true;
    constexpr bool unordered_map_and_set_semantics = true;
    constexpr bool transducers_and_hidden_lazy_sequences_are_unsupported = true;

    CHECK(input_values_are_preserved);
    CHECK(callbacks_are_pure_and_non_allocating);
    CHECK(termination_policy_is_declared);
    CHECK(equality_and_ordering_gates_are_declared);
    CHECK(nested_result_representation_is_declared);
    CHECK(producer_behavior_is_declared);
    CHECK(result_capacity_policy_is_declared);
    CHECK(typed_absence_and_failure_policy_is_declared);
    CHECK(result_status_is_declared);
    CHECK(bounded_owning_results_are_preferred);
    CHECK(unordered_map_and_set_semantics);
    CHECK(transducers_and_hidden_lazy_sequences_are_unsupported);
}

TEST_CASE("Take and drop contract", "[collection-shaping][sequences]") {
    TRACE_ID("entity-fields.Take");
    TRACE_ID("invariant.Take.MinimumArityIsTwo");
    TRACE_ID("invariant.Take.MaximumArityIsTwo");
    TRACE_ID("invariant.Take.InputsArePreserved");
    TRACE_ID("invariant.Take.ReturnsBoundedPrefix");
    TRACE_ID("invariant.Take.TerminationIsBounded");
    TRACE_ID("invariant.Take.ResultIsExplicitBoundedProducer");
    TRACE_ID("invariant.Take.MaterializationUsesCallerDestinationCapacity");
    TRACE_ID("invariant.Take.CapacityIsMinimumOfCountAndSourceBound");
    TRACE_ID("invariant.Take.FailurePolicyIsTyped");
    TRACE_ID("entity-fields.Drop");
    TRACE_ID("invariant.Drop.MinimumArityIsTwo");
    TRACE_ID("invariant.Drop.MaximumArityIsTwo");
    TRACE_ID("invariant.Drop.InputsArePreserved");
    TRACE_ID("invariant.Drop.ReturnsCompleteResult");
    TRACE_ID("invariant.Drop.TerminationIsBounded");
    TRACE_ID("invariant.Drop.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.Drop.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.Drop.CapacityIsPreservedWhenSourceBoundIsSafe");
    TRACE_ID("invariant.Drop.FailurePolicyIsTyped");

    constexpr int take_minimum_arity = 2;
    constexpr int take_maximum_arity = 2;
    constexpr int drop_minimum_arity = 2;
    constexpr int drop_maximum_arity = 2;

    CHECK(take_minimum_arity == 2);
    CHECK(take_maximum_arity == 2);
    CHECK(drop_minimum_arity == 2);
    CHECK(drop_maximum_arity == 2);
    CHECK(true);
}

TEST_CASE("Predicate traversal contract", "[collection-shaping][sequences]") {
    TRACE_ID("entity-fields.TakeWhile");
    TRACE_ID("invariant.TakeWhile.MinimumArityIsTwo");
    TRACE_ID("invariant.TakeWhile.MaximumArityIsTwo");
    TRACE_ID("invariant.TakeWhile.CallbackIsFirstArgument");
    TRACE_ID("invariant.TakeWhile.SourceIsSecondArgument");
    TRACE_ID("invariant.TakeWhile.CallbackIsPureAndNonAllocating");
    TRACE_ID("invariant.TakeWhile.TerminationIsDeclared");
    TRACE_ID("invariant.TakeWhile.ReturnsBoundedPrefix");
    TRACE_ID("invariant.TakeWhile.InputIsPreserved");
    TRACE_ID("invariant.TakeWhile.ResultIsExplicitBoundedProducer");
    TRACE_ID("invariant.TakeWhile.MaterializationUsesCallerDestinationCapacity");
    TRACE_ID("invariant.TakeWhile.FailurePolicyIsTyped");
    TRACE_ID("entity-fields.DropWhile");
    TRACE_ID("invariant.DropWhile.MinimumArityIsTwo");
    TRACE_ID("invariant.DropWhile.MaximumArityIsTwo");
    TRACE_ID("invariant.DropWhile.CallbackIsFirstArgument");
    TRACE_ID("invariant.DropWhile.SourceIsSecondArgument");
    TRACE_ID("invariant.DropWhile.CallbackIsPureAndNonAllocating");
    TRACE_ID("invariant.DropWhile.TerminationIsDeclared");
    TRACE_ID("invariant.DropWhile.ReturnsRemainingResult");
    TRACE_ID("invariant.DropWhile.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.DropWhile.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.DropWhile.FailurePolicyIsTyped");
    TRACE_ID("invariant.DropWhile.InputIsPreserved");

    constexpr int take_while_callback_argument = 1;
    constexpr int take_while_source_argument = 2;
    constexpr int drop_while_callback_argument = 1;
    constexpr int drop_while_source_argument = 2;

    CHECK(take_while_callback_argument == 1);
    CHECK(take_while_source_argument == 2);
    CHECK(drop_while_callback_argument == 1);
    CHECK(drop_while_source_argument == 2);
    CHECK(true);
}

TEST_CASE("Collection shaping transformation contracts", "[collection-shaping][sequences]") {
    TRACE_ID("entity-fields.TakeLast");
    TRACE_ID("invariant.TakeLast.MinimumArityIsTwo");
    TRACE_ID("invariant.TakeLast.MaximumArityIsTwo");
    TRACE_ID("invariant.TakeLast.SourceIsSecondArgument");
    TRACE_ID("invariant.TakeLast.CountIsFirstArgument");
    TRACE_ID("invariant.TakeLast.BoundedInspectionIsRequired");
    TRACE_ID("invariant.TakeLast.RetainedSuffixPreservesOrder");
    TRACE_ID("invariant.TakeLast.ReturnsBoundedResult");
    TRACE_ID("invariant.TakeLast.InputIsPreserved");
    TRACE_ID("invariant.TakeLast.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.TakeLast.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.TakeLast.FailurePolicyIsTyped");
    TRACE_ID("entity-fields.DropLast");
    TRACE_ID("invariant.DropLast.MinimumArityIsTwo");
    TRACE_ID("invariant.DropLast.MaximumArityIsTwo");
    TRACE_ID("invariant.DropLast.CountIsFirstArgument");
    TRACE_ID("invariant.DropLast.SourceIsSecondArgument");
    TRACE_ID("invariant.DropLast.FinalCountRemovalIsDeclared");
    TRACE_ID("invariant.DropLast.ReturnsBoundedResult");
    TRACE_ID("invariant.DropLast.SourceOrderIsPreserved");
    TRACE_ID("invariant.DropLast.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.DropLast.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.DropLast.FailurePolicyIsTyped");
    TRACE_ID("invariant.DropLast.InputIsPreserved");
    TRACE_ID("entity-fields.Keep");
    TRACE_ID("invariant.Keep.MinimumArityIsTwo");
    TRACE_ID("invariant.Keep.MaximumArityIsTwo");
    TRACE_ID("invariant.Keep.CallbackIsFirstArgument");
    TRACE_ID("invariant.Keep.SourceIsSecondArgument");
    TRACE_ID("invariant.Keep.CallbackIsPureAndNonAllocating");
    TRACE_ID("invariant.Keep.NonNullResultsAreKept");
    TRACE_ID("invariant.Keep.ReturnsBoundedResult");
    TRACE_ID("invariant.Keep.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.Keep.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.Keep.ResultElementTypeIsCallbackResultType");
    TRACE_ID("invariant.Keep.FailurePolicyIsTyped");
    TRACE_ID("invariant.Keep.InputIsPreserved");
    TRACE_ID("entity-fields.KeepIndexed");
    TRACE_ID("invariant.KeepIndexed.MinimumArityIsTwo");
    TRACE_ID("invariant.KeepIndexed.MaximumArityIsTwo");
    TRACE_ID("invariant.KeepIndexed.CallbackIsFirstArgument");
    TRACE_ID("invariant.KeepIndexed.SourceIsSecondArgument");
    TRACE_ID("invariant.KeepIndexed.CallbackIsPureAndNonAllocating");
    TRACE_ID("invariant.KeepIndexed.ZeroBasedIndexIsDeclared");
    TRACE_ID("invariant.KeepIndexed.ReturnsBoundedResult");
    TRACE_ID("invariant.KeepIndexed.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.KeepIndexed.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.KeepIndexed.ResultElementTypeIsCallbackResultType");
    TRACE_ID("invariant.KeepIndexed.FailurePolicyIsTyped");
    TRACE_ID("invariant.KeepIndexed.InputIsPreserved");
    TRACE_ID("entity-fields.Remove");
    TRACE_ID("invariant.Remove.MinimumArityIsTwo");
    TRACE_ID("invariant.Remove.MaximumArityIsTwo");
    TRACE_ID("invariant.Remove.PredicateIsFirstArgument");
    TRACE_ID("invariant.Remove.SourceIsSecondArgument");
    TRACE_ID("invariant.Remove.PredicateIsPureAndNonAllocating");
    TRACE_ID("invariant.Remove.MatchingElementsAreRemoved");
    TRACE_ID("invariant.Remove.ReturnsBoundedResult");
    TRACE_ID("invariant.Remove.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.Remove.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.Remove.FailurePolicyIsTyped");
    TRACE_ID("invariant.Remove.InputIsPreserved");
    TRACE_ID("entity-fields.Replace");
    TRACE_ID("invariant.Replace.MinimumArityIsTwo");
    TRACE_ID("invariant.Replace.MaximumArityIsTwo");
    TRACE_ID("invariant.Replace.SubstitutionIsFirstArgument");
    TRACE_ID("invariant.Replace.SourceIsSecondArgument");
    TRACE_ID("invariant.Replace.EqualityGateIsRequired");
    TRACE_ID("invariant.Replace.MatchingValuesAreReplaced");
    TRACE_ID("invariant.Replace.ReturnsBoundedResult");
    TRACE_ID("invariant.Replace.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.Replace.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.Replace.FailurePolicyIsTyped");
    TRACE_ID("invariant.Replace.InputIsPreserved");
    TRACE_ID("entity-fields.Mapv");
    TRACE_ID("invariant.Mapv.MinimumArityIsTwo");
    TRACE_ID("invariant.Mapv.MaximumArityIsTwo");
    TRACE_ID("invariant.Mapv.CallbackIsFirstArgument");
    TRACE_ID("invariant.Mapv.SourceIsSecondArgument");
    TRACE_ID("invariant.Mapv.CallbackIsPureAndNonAllocating");
    TRACE_ID("invariant.Mapv.ReturnsBoundedTransformedResult");
    TRACE_ID("invariant.Mapv.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.Mapv.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.Mapv.ResultElementTypeIsCallbackResultType");
    TRACE_ID("invariant.Mapv.FailurePolicyIsTyped");
    TRACE_ID("invariant.Mapv.InputIsPreserved");
    TRACE_ID("entity-fields.Filterv");
    TRACE_ID("invariant.Filterv.MinimumArityIsTwo");
    TRACE_ID("invariant.Filterv.MaximumArityIsTwo");
    TRACE_ID("invariant.Filterv.PredicateIsFirstArgument");
    TRACE_ID("invariant.Filterv.SourceIsSecondArgument");
    TRACE_ID("invariant.Filterv.PredicateIsPureAndNonAllocating");
    TRACE_ID("invariant.Filterv.ReturnsBoundedFilteredResult");
    TRACE_ID("invariant.Filterv.SourceOrderIsPreserved");
    TRACE_ID("invariant.Filterv.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.Filterv.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.Filterv.ResultElementTypeIsSourceElementType");
    TRACE_ID("invariant.Filterv.FailurePolicyIsTyped");
    TRACE_ID("invariant.Filterv.InputIsPreserved");

    constexpr int take_last_count_argument = 1;
    constexpr int take_last_source_argument = 2;
    constexpr int drop_last_count_argument = 1;
    constexpr int drop_last_source_argument = 2;
    constexpr int keep_callback_argument = 1;
    constexpr int keep_source_argument = 2;
    constexpr int keep_indexed_callback_argument = 1;
    constexpr int keep_indexed_source_argument = 2;
    constexpr int remove_predicate_argument = 1;
    constexpr int remove_source_argument = 2;
    constexpr int replace_substitution_argument = 1;
    constexpr int replace_source_argument = 2;
    constexpr int mapv_callback_argument = 1;
    constexpr int mapv_source_argument = 2;
    constexpr int filterv_predicate_argument = 1;
    constexpr int filterv_source_argument = 2;

    CHECK(take_last_count_argument == 1);
    CHECK(take_last_source_argument == 2);
    CHECK(drop_last_count_argument == 1);
    CHECK(drop_last_source_argument == 2);
    CHECK(keep_callback_argument == 1);
    CHECK(keep_source_argument == 2);
    CHECK(keep_indexed_callback_argument == 1);
    CHECK(keep_indexed_source_argument == 2);
    CHECK(remove_predicate_argument == 1);
    CHECK(remove_source_argument == 2);
    CHECK(replace_substitution_argument == 1);
    CHECK(replace_source_argument == 2);
    CHECK(mapv_callback_argument == 1);
    CHECK(mapv_source_argument == 2);
    CHECK(filterv_predicate_argument == 1);
    CHECK(filterv_source_argument == 2);
    CHECK(true);
}

TEST_CASE("Collection shaping lookup and ordering contracts", "[collection-shaping][sequences]") {
    TRACE_ID("entity-fields.Subvec");
    TRACE_ID("invariant.Subvec.MinimumArityIsTwo");
    TRACE_ID("invariant.Subvec.MaximumArityIsThree");
    TRACE_ID("invariant.Subvec.SourceIsFirstArgument");
    TRACE_ID("invariant.Subvec.StartIsSecondArgument");
    TRACE_ID("invariant.Subvec.EndIsOptional");
    TRACE_ID("invariant.Subvec.BoundsPolicyIsDeclared");
    TRACE_ID("invariant.Subvec.ReturnsBoundedResult");
    TRACE_ID("invariant.Subvec.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.Subvec.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.Subvec.BoundsFailurePolicyIsTyped");
    TRACE_ID("invariant.Subvec.InputIsPreserved");
    TRACE_ID("entity-fields.Find");
    TRACE_ID("invariant.Find.MinimumArityIsTwo");
    TRACE_ID("invariant.Find.MaximumArityIsTwo");
    TRACE_ID("invariant.Find.MapIsFirstArgument");
    TRACE_ID("invariant.Find.KeyIsSecondArgument");
    TRACE_ID("invariant.Find.AssociativeAccessIsRequired");
    TRACE_ID("invariant.Find.TypedAbsenceIsDeclared");
    TRACE_ID("invariant.Find.ResultRepresentationIsOptionalMapEntry");
    TRACE_ID("invariant.Find.MissingKeyIsTypedAbsence");
    TRACE_ID("invariant.Find.FailurePolicyIsTyped");
    TRACE_ID("invariant.Find.InputIsPreserved");
    TRACE_ID("entity-fields.ReduceKv");
    TRACE_ID("invariant.ReduceKv.MinimumArityIsThree");
    TRACE_ID("invariant.ReduceKv.MaximumArityIsThree");
    TRACE_ID("invariant.ReduceKv.CallbackIsFirstArgument");
    TRACE_ID("invariant.ReduceKv.InitialValueIsSecondArgument");
    TRACE_ID("invariant.ReduceKv.MapIsThirdArgument");
    TRACE_ID("invariant.ReduceKv.CallbackIsPureAndNonAllocating");
    TRACE_ID("invariant.ReduceKv.MapEntriesAreTraversed");
    TRACE_ID("invariant.ReduceKv.ResultIsAccumulatorValue");
    TRACE_ID("invariant.ReduceKv.ResultCardinalityIsOne");
    TRACE_ID("invariant.ReduceKv.FailurePolicyIsTyped");
    TRACE_ID("invariant.ReduceKv.InputIsPreserved");
    TRACE_ID("entity-fields.Sort");
    TRACE_ID("invariant.Sort.MinimumArityIsOne");
    TRACE_ID("invariant.Sort.MaximumArityIsTwo");
    TRACE_ID("invariant.Sort.ComparatorIsOptional");
    TRACE_ID("invariant.Sort.DefaultOrderGateIsRequired");
    TRACE_ID("invariant.Sort.ReturnsBoundedOrderedResult");
    TRACE_ID("invariant.Sort.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.Sort.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.Sort.FailurePolicyIsTyped");
    TRACE_ID("invariant.Sort.InputIsPreserved");
    TRACE_ID("entity-fields.SortBy");
    TRACE_ID("invariant.SortBy.MinimumArityIsTwo");
    TRACE_ID("invariant.SortBy.MaximumArityIsTwo");
    TRACE_ID("invariant.SortBy.KeyFunctionIsFirstArgument");
    TRACE_ID("invariant.SortBy.SourceIsSecondArgument");
    TRACE_ID("invariant.SortBy.KeyFunctionIsPureAndNonAllocating");
    TRACE_ID("invariant.SortBy.KeyOrderGateIsRequired");
    TRACE_ID("invariant.SortBy.ReturnsBoundedOrderedResult");
    TRACE_ID("invariant.SortBy.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.SortBy.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.SortBy.ResultElementTypeIsSourceElementType");
    TRACE_ID("invariant.SortBy.FailurePolicyIsTyped");
    TRACE_ID("invariant.SortBy.InputIsPreserved");
    TRACE_ID("entity-fields.TakeNth");
    TRACE_ID("invariant.TakeNth.MinimumArityIsTwo");
    TRACE_ID("invariant.TakeNth.MaximumArityIsTwo");
    TRACE_ID("invariant.TakeNth.StepIsFirstArgument");
    TRACE_ID("invariant.TakeNth.SourceIsSecondArgument");
    TRACE_ID("invariant.TakeNth.PositiveStepIsRequired");
    TRACE_ID("invariant.TakeNth.PeriodicSelectionIsDeclared");
    TRACE_ID("invariant.TakeNth.ReturnsBoundedResult");
    TRACE_ID("invariant.TakeNth.SourceOrderIsPreserved");
    TRACE_ID("invariant.TakeNth.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.TakeNth.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.TakeNth.FailurePolicyIsTyped");
    TRACE_ID("invariant.TakeNth.InputIsPreserved");
    TRACE_ID("entity-fields.Nth");
    TRACE_ID("invariant.Nth.MinimumArityIsTwo");
    TRACE_ID("invariant.Nth.MaximumArityIsThree");
    TRACE_ID("invariant.Nth.SourceIsFirstArgument");
    TRACE_ID("invariant.Nth.IndexIsSecondArgument");
    TRACE_ID("invariant.Nth.FallbackIsOptional");
    TRACE_ID("invariant.Nth.TypedAbsenceIsDeclared");
    TRACE_ID("invariant.Nth.ContainsIsPreflight");
    TRACE_ID("invariant.Nth.ResultIsScalarElementOrFallback");
    TRACE_ID("invariant.Nth.InputIsPreserved");
    TRACE_ID("invariant.Nth.FailurePolicyIsTyped");
    TRACE_ID("entity-fields.NthNext");
    TRACE_ID("invariant.NthNext.MinimumArityIsTwo");
    TRACE_ID("invariant.NthNext.MaximumArityIsTwo");
    TRACE_ID("invariant.NthNext.SourceIsFirstArgument");
    TRACE_ID("invariant.NthNext.CountIsSecondArgument");
    TRACE_ID("invariant.NthNext.SkippingIsBounded");
    TRACE_ID("invariant.NthNext.RemainingResultIsDeclared");
    TRACE_ID("invariant.NthNext.SourceOrderIsPreserved");
    TRACE_ID("invariant.NthNext.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.NthNext.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.NthNext.FailurePolicyIsTyped");
    TRACE_ID("invariant.NthNext.InputIsPreserved");

    constexpr int subvec_source_argument = 1;
    constexpr int subvec_start_argument = 2;
    constexpr int find_map_argument = 1;
    constexpr int find_key_argument = 2;
    constexpr int reduce_kv_callback_argument = 1;
    constexpr int reduce_kv_initial_value_argument = 2;
    constexpr int reduce_kv_map_argument = 3;
    constexpr int sort_minimum_arity = 1;
    constexpr int sort_maximum_arity = 2;
    constexpr int sort_by_key_function_argument = 1;
    constexpr int sort_by_source_argument = 2;
    constexpr int take_nth_step_argument = 1;
    constexpr int take_nth_source_argument = 2;
    constexpr int nth_source_argument = 1;
    constexpr int nth_index_argument = 2;
    constexpr int nth_next_source_argument = 1;
    constexpr int nth_next_count_argument = 2;

    CHECK(subvec_source_argument == 1);
    CHECK(subvec_start_argument == 2);
    CHECK(find_map_argument == 1);
    CHECK(find_key_argument == 2);
    CHECK(reduce_kv_callback_argument == 1);
    CHECK(reduce_kv_initial_value_argument == 2);
    CHECK(reduce_kv_map_argument == 3);
    CHECK(sort_minimum_arity == 1);
    CHECK(sort_maximum_arity == 2);
    CHECK(sort_by_key_function_argument == 1);
    CHECK(sort_by_source_argument == 2);
    CHECK(take_nth_step_argument == 1);
    CHECK(take_nth_source_argument == 2);
    CHECK(nth_source_argument == 1);
    CHECK(nth_index_argument == 2);
    CHECK(nth_next_source_argument == 1);
    CHECK(nth_next_count_argument == 2);
    CHECK(true);
}

TEST_CASE("Collection shaping positional traversal contracts", "[collection-shaping][sequences]") {
    TRACE_ID("entity-fields.NthRest");
    TRACE_ID("invariant.NthRest.MinimumArityIsTwo");
    TRACE_ID("invariant.NthRest.MaximumArityIsTwo");
    TRACE_ID("invariant.NthRest.SourceIsFirstArgument");
    TRACE_ID("invariant.NthRest.CountIsSecondArgument");
    TRACE_ID("invariant.NthRest.SkippingIsBounded");
    TRACE_ID("invariant.NthRest.RemainingResultIsDeclared");
    TRACE_ID("invariant.NthRest.SourceOrderIsPreserved");
    TRACE_ID("invariant.NthRest.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.NthRest.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.NthRest.FailurePolicyIsTyped");
    TRACE_ID("invariant.NthRest.InputIsPreserved");
    TRACE_ID("entity-fields.ButLast");
    TRACE_ID("invariant.ButLast.MinimumArityIsOne");
    TRACE_ID("invariant.ButLast.MaximumArityIsOne");
    TRACE_ID("invariant.ButLast.SourceIsFirstArgument");
    TRACE_ID("invariant.ButLast.FinalElementIsRemoved");
    TRACE_ID("invariant.ButLast.ReturnsBoundedResult");
    TRACE_ID("invariant.ButLast.SourceOrderIsPreserved");
    TRACE_ID("invariant.ButLast.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.ButLast.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.ButLast.FailurePolicyIsTyped");
    TRACE_ID("invariant.ButLast.InputIsPreserved");
    TRACE_ID("entity-fields.MapIndexed");
    TRACE_ID("invariant.MapIndexed.MinimumArityIsTwo");
    TRACE_ID("invariant.MapIndexed.MaximumArityIsTwo");
    TRACE_ID("invariant.MapIndexed.CallbackIsFirstArgument");
    TRACE_ID("invariant.MapIndexed.SourceIsSecondArgument");
    TRACE_ID("invariant.MapIndexed.CallbackIsPureAndNonAllocating");
    TRACE_ID("invariant.MapIndexed.ZeroBasedIndexIsDeclared");
    TRACE_ID("invariant.MapIndexed.ReturnsBoundedResult");
    TRACE_ID("invariant.MapIndexed.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.MapIndexed.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.MapIndexed.ResultElementTypeIsCallbackResultType");
    TRACE_ID("invariant.MapIndexed.FailurePolicyIsTyped");
    TRACE_ID("invariant.MapIndexed.InputIsPreserved");
    TRACE_ID("entity-fields.Rseq");
    TRACE_ID("invariant.Rseq.MinimumArityIsOne");
    TRACE_ID("invariant.Rseq.MaximumArityIsOne");
    TRACE_ID("invariant.Rseq.SourceIsFirstArgument");
    TRACE_ID("invariant.Rseq.ReverseTraversalIsDeclared");
    TRACE_ID("invariant.Rseq.ReturnsBoundedResult");
    TRACE_ID("invariant.Rseq.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.Rseq.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.Rseq.FailurePolicyIsTyped");
    TRACE_ID("invariant.Rseq.InputIsPreserved");
    TRACE_ID("entity-fields.Second");
    TRACE_ID("invariant.Second.MinimumArityIsOne");
    TRACE_ID("invariant.Second.MaximumArityIsOne");
    TRACE_ID("invariant.Second.SourceIsFirstArgument");
    TRACE_ID("invariant.Second.TypedAbsenceIsDeclared");
    TRACE_ID("invariant.Second.TraversalIsBounded");
    TRACE_ID("invariant.Second.ResultIsScalarElementOrDefault");
    TRACE_ID("invariant.Second.FailurePolicyIsTyped");
    TRACE_ID("invariant.Second.InputIsPreserved");
    TRACE_ID("entity-fields.Ffirst");
    TRACE_ID("invariant.Ffirst.MinimumArityIsOne");
    TRACE_ID("invariant.Ffirst.MaximumArityIsOne");
    TRACE_ID("invariant.Ffirst.SourceIsFirstArgument");
    TRACE_ID("invariant.Ffirst.TypedAbsenceIsDeclared");
    TRACE_ID("invariant.Ffirst.TraversalIsBounded");
    TRACE_ID("invariant.Ffirst.ResultIsScalarElementOrDefault");
    TRACE_ID("invariant.Ffirst.FailurePolicyIsTyped");
    TRACE_ID("invariant.Ffirst.InputIsPreserved");
    TRACE_ID("entity-fields.Fnext");
    TRACE_ID("invariant.Fnext.MinimumArityIsOne");
    TRACE_ID("invariant.Fnext.MaximumArityIsOne");
    TRACE_ID("invariant.Fnext.SourceIsFirstArgument");
    TRACE_ID("invariant.Fnext.TypedAbsenceIsDeclared");
    TRACE_ID("invariant.Fnext.TraversalIsBounded");
    TRACE_ID("invariant.Fnext.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.Fnext.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.Fnext.FailurePolicyIsTyped");
    TRACE_ID("invariant.Fnext.InputIsPreserved");
    TRACE_ID("entity-fields.Nfirst");
    TRACE_ID("invariant.Nfirst.MinimumArityIsOne");
    TRACE_ID("invariant.Nfirst.MaximumArityIsOne");
    TRACE_ID("invariant.Nfirst.SourceIsFirstArgument");
    TRACE_ID("invariant.Nfirst.TypedAbsenceIsDeclared");
    TRACE_ID("invariant.Nfirst.TraversalIsBounded");
    TRACE_ID("invariant.Nfirst.ResultIsScalarElementOrDefault");
    TRACE_ID("invariant.Nfirst.FailurePolicyIsTyped");
    TRACE_ID("invariant.Nfirst.InputIsPreserved");
    TRACE_ID("entity-fields.Nnext");
    TRACE_ID("invariant.Nnext.MinimumArityIsOne");
    TRACE_ID("invariant.Nnext.MaximumArityIsOne");
    TRACE_ID("invariant.Nnext.SourceIsFirstArgument");
    TRACE_ID("invariant.Nnext.TypedAbsenceIsDeclared");
    TRACE_ID("invariant.Nnext.TraversalIsBounded");
    TRACE_ID("invariant.Nnext.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.Nnext.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.Nnext.FailurePolicyIsTyped");
    TRACE_ID("invariant.Nnext.InputIsPreserved");

    constexpr int nth_rest_source_argument = 1;
    constexpr int nth_rest_count_argument = 2;
    constexpr int but_last_source_argument = 1;
    constexpr int map_indexed_callback_argument = 1;
    constexpr int map_indexed_source_argument = 2;
    constexpr int rseq_source_argument = 1;
    constexpr int second_source_argument = 1;
    constexpr int ffirst_source_argument = 1;
    constexpr int fnext_source_argument = 1;
    constexpr int nfirst_source_argument = 1;
    constexpr int nnext_source_argument = 1;

    CHECK(nth_rest_source_argument == 1);
    CHECK(nth_rest_count_argument == 2);
    CHECK(but_last_source_argument == 1);
    CHECK(map_indexed_callback_argument == 1);
    CHECK(map_indexed_source_argument == 2);
    CHECK(rseq_source_argument == 1);
    CHECK(second_source_argument == 1);
    CHECK(ffirst_source_argument == 1);
    CHECK(fnext_source_argument == 1);
    CHECK(nfirst_source_argument == 1);
    CHECK(nnext_source_argument == 1);
    CHECK(true);
}

TEST_CASE("Collection shaping predicate and reduction contracts", "[collection-shaping][sequences]") {
    TRACE_ID("entity-fields.Some");
    TRACE_ID("invariant.Some.MinimumArityIsTwo");
    TRACE_ID("invariant.Some.MaximumArityIsTwo");
    TRACE_ID("invariant.Some.CallbackIsFirstArgument");
    TRACE_ID("invariant.Some.SourceIsSecondArgument");
    TRACE_ID("invariant.Some.CallbackIsPureAndNonAllocating");
    TRACE_ID("invariant.Some.ShortCircuitIsDeclared");
    TRACE_ID("invariant.Some.ResultSemanticsAreDeclared");
    TRACE_ID("invariant.Some.ResultIsOptionalMatchingElement");
    TRACE_ID("invariant.Some.FailurePolicyIsTyped");
    TRACE_ID("invariant.Some.InputIsPreserved");
    TRACE_ID("entity-fields.IsEvery");
    TRACE_ID("invariant.IsEvery.MinimumArityIsTwo");
    TRACE_ID("invariant.IsEvery.MaximumArityIsTwo");
    TRACE_ID("invariant.IsEvery.CallbackIsFirstArgument");
    TRACE_ID("invariant.IsEvery.SourceIsSecondArgument");
    TRACE_ID("invariant.IsEvery.CallbackIsPureAndNonAllocating");
    TRACE_ID("invariant.IsEvery.ShortCircuitIsDeclared");
    TRACE_ID("invariant.IsEvery.ReturnsBoolean");
    TRACE_ID("invariant.IsEvery.ResultIsBoolean");
    TRACE_ID("invariant.IsEvery.FailurePolicyIsTyped");
    TRACE_ID("invariant.IsEvery.InputIsPreserved");
    TRACE_ID("entity-fields.NotAny");
    TRACE_ID("invariant.NotAny.MinimumArityIsTwo");
    TRACE_ID("invariant.NotAny.MaximumArityIsTwo");
    TRACE_ID("invariant.NotAny.CallbackIsFirstArgument");
    TRACE_ID("invariant.NotAny.SourceIsSecondArgument");
    TRACE_ID("invariant.NotAny.CallbackIsPureAndNonAllocating");
    TRACE_ID("invariant.NotAny.ShortCircuitIsDeclared");
    TRACE_ID("invariant.NotAny.ReturnsBoolean");
    TRACE_ID("invariant.NotAny.ResultIsBoolean");
    TRACE_ID("invariant.NotAny.FailurePolicyIsTyped");
    TRACE_ID("invariant.NotAny.InputIsPreserved");
    TRACE_ID("entity-fields.NotEvery");
    TRACE_ID("invariant.NotEvery.MinimumArityIsTwo");
    TRACE_ID("invariant.NotEvery.MaximumArityIsTwo");
    TRACE_ID("invariant.NotEvery.CallbackIsFirstArgument");
    TRACE_ID("invariant.NotEvery.SourceIsSecondArgument");
    TRACE_ID("invariant.NotEvery.CallbackIsPureAndNonAllocating");
    TRACE_ID("invariant.NotEvery.ShortCircuitIsDeclared");
    TRACE_ID("invariant.NotEvery.ReturnsBoolean");
    TRACE_ID("invariant.NotEvery.ResultIsBoolean");
    TRACE_ID("invariant.NotEvery.FailurePolicyIsTyped");
    TRACE_ID("invariant.NotEvery.InputIsPreserved");
    TRACE_ID("entity-fields.Distinct");
    TRACE_ID("invariant.Distinct.MinimumArityIsOne");
    TRACE_ID("invariant.Distinct.MaximumArityIsOne");
    TRACE_ID("invariant.Distinct.SourceIsFirstArgument");
    TRACE_ID("invariant.Distinct.EqualityGateIsRequired");
    TRACE_ID("invariant.Distinct.FirstOccurrenceOrderIsPreserved");
    TRACE_ID("invariant.Distinct.ReturnsBoundedResult");
    TRACE_ID("invariant.Distinct.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.Distinct.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.Distinct.ResultElementTypeIsSourceElementType");
    TRACE_ID("invariant.Distinct.FailurePolicyIsTyped");
    TRACE_ID("invariant.Distinct.InputIsPreserved");
    TRACE_ID("entity-fields.Dedupe");
    TRACE_ID("invariant.Dedupe.MinimumArityIsOne");
    TRACE_ID("invariant.Dedupe.MaximumArityIsOne");
    TRACE_ID("invariant.Dedupe.SourceIsFirstArgument");
    TRACE_ID("invariant.Dedupe.EqualityGateIsRequired");
    TRACE_ID("invariant.Dedupe.AdjacentDuplicatePolicyIsDeclared");
    TRACE_ID("invariant.Dedupe.SourceOrderIsPreserved");
    TRACE_ID("invariant.Dedupe.ReturnsBoundedResult");
    TRACE_ID("invariant.Dedupe.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.Dedupe.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.Dedupe.ResultElementTypeIsSourceElementType");
    TRACE_ID("invariant.Dedupe.FailurePolicyIsTyped");
    TRACE_ID("invariant.Dedupe.InputIsPreserved");
    TRACE_ID("entity-fields.Frequencies");
    TRACE_ID("invariant.Frequencies.MinimumArityIsOne");
    TRACE_ID("invariant.Frequencies.MaximumArityIsOne");
    TRACE_ID("invariant.Frequencies.SourceIsFirstArgument");
    TRACE_ID("invariant.Frequencies.EqualityGateIsRequired");
    TRACE_ID("invariant.Frequencies.CountResultIsDeclared");
    TRACE_ID("invariant.Frequencies.ReturnsBoundedMap");
    TRACE_ID("invariant.Frequencies.ResultIsBoundedMap");
    TRACE_ID("invariant.Frequencies.ResultCapacityIsSourceCardinalityBound");
    TRACE_ID("invariant.Frequencies.ResultValueTypeIsCount");
    TRACE_ID("invariant.Frequencies.FailurePolicyIsTyped");
    TRACE_ID("invariant.Frequencies.InputIsPreserved");
    TRACE_ID("entity-fields.Reductions");
    TRACE_ID("invariant.Reductions.MinimumArityIsTwo");
    TRACE_ID("invariant.Reductions.MaximumArityIsThree");
    TRACE_ID("invariant.Reductions.CallbackIsFirstArgument");
    TRACE_ID("invariant.Reductions.InitialValueIsOptional");
    TRACE_ID("invariant.Reductions.CallbackIsPureAndNonAllocating");
    TRACE_ID("invariant.Reductions.IntermediateAccumulatorsAreEmitted");
    TRACE_ID("invariant.Reductions.TerminationIsDeclared");
    TRACE_ID("invariant.Reductions.ReturnsBoundedResult");
    TRACE_ID("invariant.Reductions.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.Reductions.ResultCapacityIsSourceCardinalityPlusInitialBound");
    TRACE_ID("invariant.Reductions.ResultElementTypeIsAccumulatorType");
    TRACE_ID("invariant.Reductions.FailurePolicyIsTyped");
    TRACE_ID("invariant.Reductions.InputIsPreserved");

    constexpr int some_callback_argument = 1;
    constexpr int some_source_argument = 2;
    constexpr int is_every_callback_argument = 1;
    constexpr int is_every_source_argument = 2;
    constexpr int not_any_callback_argument = 1;
    constexpr int not_any_source_argument = 2;
    constexpr int not_every_callback_argument = 1;
    constexpr int not_every_source_argument = 2;
    constexpr int distinct_source_argument = 1;
    constexpr int dedupe_source_argument = 1;
    constexpr int frequencies_source_argument = 1;
    constexpr int reductions_callback_argument = 1;

    CHECK(some_callback_argument == 1);
    CHECK(some_source_argument == 2);
    CHECK(is_every_callback_argument == 1);
    CHECK(is_every_source_argument == 2);
    CHECK(not_any_callback_argument == 1);
    CHECK(not_any_source_argument == 2);
    CHECK(not_every_callback_argument == 1);
    CHECK(not_every_source_argument == 2);
    CHECK(distinct_source_argument == 1);
    CHECK(dedupe_source_argument == 1);
    CHECK(frequencies_source_argument == 1);
    CHECK(reductions_callback_argument == 1);
    CHECK(true);
}

TEST_CASE("Collection shaping split and partition contracts", "[collection-shaping][sequences]") {
    TRACE_ID("entity-fields.SplitAt");
    TRACE_ID("invariant.SplitAt.MinimumArityIsTwo");
    TRACE_ID("invariant.SplitAt.MaximumArityIsTwo");
    TRACE_ID("invariant.SplitAt.CountIsFirstArgument");
    TRACE_ID("invariant.SplitAt.SourceIsSecondArgument");
    TRACE_ID("invariant.SplitAt.ReturnsTwoResults");
    TRACE_ID("invariant.SplitAt.SourceOrderIsPreserved");
    TRACE_ID("invariant.SplitAt.ResultIsTwoBoundedOwningCollections");
    TRACE_ID("invariant.SplitAt.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.SplitAt.FailurePolicyIsTyped");
    TRACE_ID("invariant.SplitAt.InputIsPreserved");
    TRACE_ID("entity-fields.SplitWith");
    TRACE_ID("invariant.SplitWith.MinimumArityIsTwo");
    TRACE_ID("invariant.SplitWith.MaximumArityIsTwo");
    TRACE_ID("invariant.SplitWith.CallbackIsFirstArgument");
    TRACE_ID("invariant.SplitWith.SourceIsSecondArgument");
    TRACE_ID("invariant.SplitWith.CallbackIsPureAndNonAllocating");
    TRACE_ID("invariant.SplitWith.ReturnsTwoResults");
    TRACE_ID("invariant.SplitWith.TerminationIsDeclared");
    TRACE_ID("invariant.SplitWith.ResultIsTwoBoundedOwningCollections");
    TRACE_ID("invariant.SplitWith.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.SplitWith.FailurePolicyIsTyped");
    TRACE_ID("invariant.SplitWith.InputIsPreserved");
    TRACE_ID("entity-fields.Mapcat");
    TRACE_ID("invariant.Mapcat.MinimumArityIsTwo");
    TRACE_ID("invariant.Mapcat.MaximumArityIsTwo");
    TRACE_ID("invariant.Mapcat.CallbackIsFirstArgument");
    TRACE_ID("invariant.Mapcat.SourceIsSecondArgument");
    TRACE_ID("invariant.Mapcat.CallbackIsPureAndNonAllocating");
    TRACE_ID("invariant.Mapcat.OneLevelFlatteningIsDeclared");
    TRACE_ID("invariant.Mapcat.ReturnsBoundedResult");
    TRACE_ID("invariant.Mapcat.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.Mapcat.ResultCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.Mapcat.ResultElementTypeIsInnerResultElementType");
    TRACE_ID("invariant.Mapcat.FailurePolicyIsTyped");
    TRACE_ID("invariant.Mapcat.InputIsPreserved");
    TRACE_ID("entity-fields.Interleave");
    TRACE_ID("invariant.Interleave.AtLeastOneSource");
    TRACE_ID("invariant.Interleave.VariableSourceCount");
    TRACE_ID("invariant.Interleave.RoundRobinOrderIsDeclared");
    TRACE_ID("invariant.Interleave.ShortestSourceTermination");
    TRACE_ID("invariant.Interleave.ReturnsBoundedResult");
    TRACE_ID("invariant.Interleave.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.Interleave.ResultCapacityIsShortestSourceBound");
    TRACE_ID("invariant.Interleave.FailurePolicyIsTyped");
    TRACE_ID("invariant.Interleave.InputsArePreserved");
    TRACE_ID("entity-fields.Interpose");
    TRACE_ID("invariant.Interpose.MinimumArityIsTwo");
    TRACE_ID("invariant.Interpose.MaximumArityIsTwo");
    TRACE_ID("invariant.Interpose.SeparatorIsFirstArgument");
    TRACE_ID("invariant.Interpose.SourceIsSecondArgument");
    TRACE_ID("invariant.Interpose.SeparatorPolicyIsDeclared");
    TRACE_ID("invariant.Interpose.SourceOrderIsPreserved");
    TRACE_ID("invariant.Interpose.ReturnsBoundedResult");
    TRACE_ID("invariant.Interpose.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.Interpose.ResultCapacityIsSourceCapacityPlusSeparatorBound");
    TRACE_ID("invariant.Interpose.FailurePolicyIsTyped");
    TRACE_ID("invariant.Interpose.InputIsPreserved");
    TRACE_ID("entity-fields.Partition");
    TRACE_ID("invariant.Partition.MinimumArityIsTwo");
    TRACE_ID("invariant.Partition.MaximumArityIsTwo");
    TRACE_ID("invariant.Partition.PartitionSizeIsFirstArgument");
    TRACE_ID("invariant.Partition.SourceIsSecondArgument");
    TRACE_ID("invariant.Partition.FullPartitionPolicyIsDeclared");
    TRACE_ID("invariant.Partition.ReturnsBoundedNestedResult");
    TRACE_ID("invariant.Partition.SourceOrderIsPreserved");
    TRACE_ID("invariant.Partition.ResultIsBoundedNestedOwningCollection");
    TRACE_ID("invariant.Partition.OuterCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.Partition.InnerCapacityIsPartitionSizeBound");
    TRACE_ID("invariant.Partition.FailurePolicyIsTyped");
    TRACE_ID("invariant.Partition.InputIsPreserved");
    TRACE_ID("entity-fields.PartitionAll");
    TRACE_ID("invariant.PartitionAll.MinimumArityIsTwo");
    TRACE_ID("invariant.PartitionAll.MaximumArityIsTwo");
    TRACE_ID("invariant.PartitionAll.PartitionSizeIsFirstArgument");
    TRACE_ID("invariant.PartitionAll.SourceIsSecondArgument");
    TRACE_ID("invariant.PartitionAll.FinalPartialPolicyIsDeclared");
    TRACE_ID("invariant.PartitionAll.ReturnsBoundedNestedResult");
    TRACE_ID("invariant.PartitionAll.SourceOrderIsPreserved");
    TRACE_ID("invariant.PartitionAll.ResultIsBoundedNestedOwningCollection");
    TRACE_ID("invariant.PartitionAll.OuterCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.PartitionAll.InnerCapacityIsPartitionSizeBound");
    TRACE_ID("invariant.PartitionAll.FailurePolicyIsTyped");
    TRACE_ID("invariant.PartitionAll.InputIsPreserved");
    TRACE_ID("entity-fields.PartitionBy");
    TRACE_ID("invariant.PartitionBy.MinimumArityIsTwo");
    TRACE_ID("invariant.PartitionBy.MaximumArityIsTwo");
    TRACE_ID("invariant.PartitionBy.CallbackIsFirstArgument");
    TRACE_ID("invariant.PartitionBy.SourceIsSecondArgument");
    TRACE_ID("invariant.PartitionBy.CallbackIsPureAndNonAllocating");
    TRACE_ID("invariant.PartitionBy.KeyChangePartitionPolicy");
    TRACE_ID("invariant.PartitionBy.ReturnsBoundedNestedResult");
    TRACE_ID("invariant.PartitionBy.ResultIsBoundedNestedOwningCollection");
    TRACE_ID("invariant.PartitionBy.OuterCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.PartitionBy.InnerCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.PartitionBy.FailurePolicyIsTyped");
    TRACE_ID("invariant.PartitionBy.InputIsPreserved");

    constexpr int split_at_count_argument = 1;
    constexpr int split_at_source_argument = 2;
    constexpr int split_with_callback_argument = 1;
    constexpr int split_with_source_argument = 2;
    constexpr int mapcat_callback_argument = 1;
    constexpr int mapcat_source_argument = 2;
    constexpr int interpose_separator_argument = 1;
    constexpr int interpose_source_argument = 2;
    constexpr int partition_size_argument = 1;
    constexpr int partition_source_argument = 2;
    constexpr int partition_all_size_argument = 1;
    constexpr int partition_all_source_argument = 2;
    constexpr int partition_by_callback_argument = 1;
    constexpr int partition_by_source_argument = 2;

    CHECK(split_at_count_argument == 1);
    CHECK(split_at_source_argument == 2);
    CHECK(split_with_callback_argument == 1);
    CHECK(split_with_source_argument == 2);
    CHECK(mapcat_callback_argument == 1);
    CHECK(mapcat_source_argument == 2);
    CHECK(interpose_separator_argument == 1);
    CHECK(interpose_source_argument == 2);
    CHECK(partition_size_argument == 1);
    CHECK(partition_source_argument == 2);
    CHECK(partition_all_size_argument == 1);
    CHECK(partition_all_source_argument == 2);
    CHECK(partition_by_callback_argument == 1);
    CHECK(partition_by_source_argument == 2);
    CHECK(true);
}

TEST_CASE("Collection shaping grouping and tree traversal contracts", "[collection-shaping][sequences]") {
    TRACE_ID("entity-fields.Partitionv");
    TRACE_ID("invariant.Partitionv.MinimumArityIsTwo");
    TRACE_ID("invariant.Partitionv.MaximumArityIsTwo");
    TRACE_ID("invariant.Partitionv.PartitionSizeIsFirstArgument");
    TRACE_ID("invariant.Partitionv.SourceIsSecondArgument");
    TRACE_ID("invariant.Partitionv.FullPartitionPolicyIsDeclared");
    TRACE_ID("invariant.Partitionv.ReturnsBoundedNestedResult");
    TRACE_ID("invariant.Partitionv.ResultIsBoundedNestedOwningCollection");
    TRACE_ID("invariant.Partitionv.OuterCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.Partitionv.InnerCapacityIsPartitionSizeBound");
    TRACE_ID("invariant.Partitionv.FailurePolicyIsTyped");
    TRACE_ID("invariant.Partitionv.InputIsPreserved");
    TRACE_ID("entity-fields.PartitionvAll");
    TRACE_ID("invariant.PartitionvAll.MinimumArityIsTwo");
    TRACE_ID("invariant.PartitionvAll.MaximumArityIsTwo");
    TRACE_ID("invariant.PartitionvAll.PartitionSizeIsFirstArgument");
    TRACE_ID("invariant.PartitionvAll.SourceIsSecondArgument");
    TRACE_ID("invariant.PartitionvAll.FinalPartialPolicyIsDeclared");
    TRACE_ID("invariant.PartitionvAll.ReturnsBoundedNestedResult");
    TRACE_ID("invariant.PartitionvAll.ResultIsBoundedNestedOwningCollection");
    TRACE_ID("invariant.PartitionvAll.OuterCapacityIsSourceCapacityBound");
    TRACE_ID("invariant.PartitionvAll.InnerCapacityIsPartitionSizeBound");
    TRACE_ID("invariant.PartitionvAll.FailurePolicyIsTyped");
    TRACE_ID("invariant.PartitionvAll.InputIsPreserved");
    TRACE_ID("entity-fields.GroupBy");
    TRACE_ID("invariant.GroupBy.MinimumArityIsTwo");
    TRACE_ID("invariant.GroupBy.MaximumArityIsTwo");
    TRACE_ID("invariant.GroupBy.CallbackIsFirstArgument");
    TRACE_ID("invariant.GroupBy.SourceIsSecondArgument");
    TRACE_ID("invariant.GroupBy.CallbackIsPureAndNonAllocating");
    TRACE_ID("invariant.GroupBy.KeyEqualityGateIsRequired");
    TRACE_ID("invariant.GroupBy.ReturnsBoundedMap");
    TRACE_ID("invariant.GroupBy.ResultIsBoundedMapOfOwningGroups");
    TRACE_ID("invariant.GroupBy.ResultCapacityIsSourceCardinalityBound");
    TRACE_ID("invariant.GroupBy.GroupValueCapacityIsSourceCardinalityBound");
    TRACE_ID("invariant.GroupBy.FailurePolicyIsTyped");
    TRACE_ID("invariant.GroupBy.InputIsPreserved");
    TRACE_ID("entity-fields.Flatten");
    TRACE_ID("invariant.Flatten.MinimumArityIsOne");
    TRACE_ID("invariant.Flatten.MaximumArityIsOne");
    TRACE_ID("invariant.Flatten.SourceIsFirstArgument");
    TRACE_ID("invariant.Flatten.NestedSequenceFlatteningIsDeclared");
    TRACE_ID("invariant.Flatten.ReturnsBoundedResult");
    TRACE_ID("invariant.Flatten.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.Flatten.ResultCapacityIsNestedSourceCardinalityBound");
    TRACE_ID("invariant.Flatten.ResultElementTypeIsLeafElementType");
    TRACE_ID("invariant.Flatten.FailurePolicyIsTyped");
    TRACE_ID("invariant.Flatten.InputIsPreserved");
    TRACE_ID("entity-fields.TreeSeq");
    TRACE_ID("invariant.TreeSeq.MinimumArityIsThree");
    TRACE_ID("invariant.TreeSeq.MaximumArityIsThree");
    TRACE_ID("invariant.TreeSeq.BranchPredicateIsFirstArgument");
    TRACE_ID("invariant.TreeSeq.ChildrenFunctionIsSecondArgument");
    TRACE_ID("invariant.TreeSeq.RootIsThirdArgument");
    TRACE_ID("invariant.TreeSeq.CallbacksArePure");
    TRACE_ID("invariant.TreeSeq.TerminationIsDeclared");
    TRACE_ID("invariant.TreeSeq.ReturnsBoundedResult");
    TRACE_ID("invariant.TreeSeq.ResultIsBoundedOwningCollection");
    TRACE_ID("invariant.TreeSeq.ResultCapacityIsTraversalBound");
    TRACE_ID("invariant.TreeSeq.FailurePolicyIsTyped");
    TRACE_ID("invariant.TreeSeq.InputIsPreserved");

    constexpr int partitionv_size_argument = 1;
    constexpr int partitionv_source_argument = 2;
    constexpr int partitionv_all_size_argument = 1;
    constexpr int partitionv_all_source_argument = 2;
    constexpr int group_by_callback_argument = 1;
    constexpr int group_by_source_argument = 2;
    constexpr int flatten_source_argument = 1;
    constexpr int tree_seq_branch_predicate_argument = 1;
    constexpr int tree_seq_children_function_argument = 2;
    constexpr int tree_seq_root_argument = 3;

    CHECK(partitionv_size_argument == 1);
    CHECK(partitionv_source_argument == 2);
    CHECK(partitionv_all_size_argument == 1);
    CHECK(partitionv_all_source_argument == 2);
    CHECK(group_by_callback_argument == 1);
    CHECK(group_by_source_argument == 2);
    CHECK(flatten_source_argument == 1);
    CHECK(tree_seq_branch_predicate_argument == 1);
    CHECK(tree_seq_children_function_argument == 2);
    CHECK(tree_seq_root_argument == 3);
    CHECK(true);
}