#!/usr/bin/env python3
"""Generate cljonic.hpp from the public modular header."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


LOCAL_INCLUDE = re.compile(r"^(?P<indent>\s*)#include <(?P<name>cljonic-[^>]+)>\s*$")


class AmalgamationError(RuntimeError):
    """Raised when the local header graph cannot be amalgamated."""


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--root", default="cljonic-core.hpp")
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def resolve_header(source_dir: Path, name: str) -> Path:
    path = source_dir / name
    if path.suffix != ".hpp" or not name.startswith("cljonic-"):
        raise AmalgamationError(f"unsupported local header: {name}")
    if not path.is_file():
        raise AmalgamationError(f"local header not found: {path}")
    return path


def expand_header(path: Path, source_dir: Path, states: dict[Path, str]) -> list[str]:
    state = states.get(path)
    if state == "visiting":
        raise AmalgamationError(f"local header include cycle at: {path}")
    if state == "emitted":
        return []

    states[path] = "visiting"
    output: list[str] = [f"// Begin {path.relative_to(source_dir)}\n"]
    for line in path.read_text(encoding="utf-8").splitlines(keepends=True):
        match = LOCAL_INCLUDE.match(line.rstrip("\n"))
        if match:
            dependency = resolve_header(source_dir, match.group("name"))
            output.extend(expand_header(dependency, source_dir, states))
        else:
            output.append(line)
    output.append(f"// End {path.relative_to(source_dir)}\n")
    states[path] = "emitted"
    return output


def generate(source_dir: Path, root: str, output: Path) -> None:
    source_dir = source_dir.resolve()
    root_path = resolve_header(source_dir, root)
    lines = ["// Generated by scripts/amalgamate.py. Do not edit.\n", "\n"]
    lines.extend(expand_header(root_path, source_dir, {}))
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("".join(lines), encoding="utf-8", newline="\n")


def main() -> int:
    arguments = parse_arguments()
    try:
        generate(arguments.source_dir, arguments.root, arguments.output)
    except (AmalgamationError, OSError) as error:
        raise SystemExit(f"amalgamate: error: {error}") from error
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
