#pragma once

#if !defined(CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT)
#define CLJONIC_COLLECTION_MAXIMUM_ELEMENT_COUNT 1000
#endif

#define CLJONIC_STRINGIFY_INNER(x) #x
#define CLJONIC_STRINGIFY(x) CLJONIC_STRINGIFY_INNER(x)